zproject_bindings_ruby.gsl
zproject_class_api.gsl

Solution: Make a special case for this coercion

Problem: Typical arg coercion in ruby bindings doesn't work for self_p

---

zproject_bindings_qml.gsl

Solution: Make a case for this.

Problem: Generated QML bindings ignore the "by_reference" flag.

---

zproject_bindings_qml.gsl
zproject_class_api.gsl

Solution: Interpret affirmative "fresh" to mean NOT "constant"

Problem: C header generator for strings doesn't recognize "fresh" attribute

---

zproject_autoconf.gsl
zproject_automake.gsl

Solution: backport --with-makecert from CZMQ

Problem: need more control over building/installing mains

---

zproject_bindings_qml.gsl
zproject_bindings_ruby.gsl
zproject_class_api.gsl

Solution: Add special 'format' argument type which does this
Also add size_t support...

Problem: Unable to represent printf-style format/vararg argument pair in class API.

---

zproject_android.gsl
zproject_automake.gsl
zproject_class.gsl
zproject_class_api.gsl
zproject_cmake.gsl
zproject_cygwin.gsl
zproject_docs.gsl
zproject_mingw32.gsl
zproject_vs2008.gsl
zproject_vs2010.gsl
zproject_vs2012.gsl
zproject_vs2013.gsl

A couple of changes in support of implementing zyre's event class using zproject CLASS api.

Zyre event fixes

---

project.xml
src/Makemodule.am
zproject.gsl
zproject_bindings_python.gsl
zproject_git.gsl

Solution: Generate Python bindings using ctypes

Problem: No support for python bindings

---

zproject_automake.gsl
zproject_bindings_python.gsl
zproject_vs2008.gsl
zproject_vs2010.gsl
zproject_vs2012.gsl
zproject_vs2013.gsl

I found a couple of issues with my recent pull requests, which these commits fix.
More information in the individual commit messages.

Fixes for issues to do with my recent pull requests

---

zproject_bindings_python.gsl
zproject_class_api.gsl

Details in individual commit messages.

Various commits in aid of generating CZMQ zmsg

---

README.md
README.txt

Solution: Merge changes from README.md into README.txt and generate with
gitdown

Problem: README.md has been modified but is generated by gitdown

---

zproject_class.gsl
zproject_class_api.gsl

details in individual changes.

Patches required for CZMQ zsock CLASS api, and implicit creation of print/test methods

---

zproject_class.gsl
zproject_known_projects.xml
zproject_projects.gsl

Add ability to specify custom include file for known project definition; add jemalloc to known projects list.

Add ability to specify custom include file for known project definition; add jemalloc to known projects list

---

zproject_autoconf.gsl

Solution: Add the check
See https://github.com/zeromq/czmq/pull/943

Problem: Autoconf does not check for bigendian

---

zproject_automake.gsl

Solution: change _servicedir template to use prefix/lib instead

Problem: systemd files in wrong dir

---

zproject_bindings_python.gsl

Solution: Generate constant values as class members

Problem: Python bindings did not generate constants.

---

zproject_bindings_python.gsl

Being able to test whether the class is valid is not really related to whether you can destroy the class.

Problem: Python bindings boolean test was inside destructor test

---

CMakeLists.txt
README.md
configure.ac
project.xml
src/Makemodule.am
zproject.gsl
zproject_actor.gsl

Solution: Allow actor skeleton to be generated
Therefore I introduced a new xml tag <actor/> which can be used
with the same attributes as classes.
Solves #183

Problem: CLASS skeletons for actors need manual rewriting

---

README.md
README.txt
project.xml

Solution: Write a little bit about them

Problem: Documation is a bit sparse about actors

---

zproject_known_projects.xml
zproject_projects.gsl

Solution: add to list of known projects.

Problem: need Malamute support

---

zproject_actor.gsl

Solution: Properly free allocated memory
Problem: No ability to generate private actor class
Solution: add handling of private attribute

Problem: memory leak in actor class

---

zproject_automake.gsl

Solution: has to include project classes header, and any private
headers.

Problem: EXTRA_DIST was incomplete

---

Makefile.am
src/Makemodule.am
zproject_automake.gsl

Solution: fixed for automake at least.

Problem: does not put LICENSE, README, CONTRIBUTING into packages

---

zproject_ci.gsl
zproject_qt_android.gsl

This PR makes the CI build scripts compatible with OSX on Travis. Fixes #208

Travis ci osx

---

zproject_actor.gsl

Actor generation improvement

---

project.xml
zproject.gsl
zproject_automake.gsl
zproject_bench.gsl

Solution: Extend zproject to generate a lean benchmarking suite and run them with 'make benchmarks'.

Problem: There is currently no support for easily benchmarking you're stuff

---

zproject_automake.gsl

Solution: Add make targets to the Makefile.am

Problem:  Need valgrind tools memcheck and callgrind for selftest and benchmarks

---

zproject_automake.gsl

Solution: make the bench target a .PHONY target

Problem: 'make bench' is only execute if sources change

---

AUTHORS
CONTRIBUTING.md
zproject_autoconf.gsl
zproject_class.gsl

which is used i.e in czmq for HAVE_LIBUUID
Solution: Add the prefix
Also some small simplifications in the GSL code for the pkg config checks.

Problem: The 'HAVE_*' define omits the LIB prefix 

---

README.md
README.txt

Solution: Add a link to the contribution guideline in the hints for contributers

Problem: Readme doesn't contain latest contribution changes

---

autogen.sh
configure.ac
project.xml
src/Makemodule.am
zproject.gsl
zproject_bindings_jni.gsl

Problem: lacking stub for jni binding

---

.gitignore
zproject_bindings_jni.gsl

Generating stub for java classes

---

zproject_bindings_jni.gsl

Solution: starting to map C types to Java

Problem: lack basic API interface

---

zproject_bindings_jni.gsl

Solution: generate skeleton C file for each class.

Problem: need to flesh out JNI binding

---

zproject_bindings_jni.gsl

Add these to list of types we understand.

Problem: JNI generator doesn't recognize project's own classes

---

zproject_automake.gsl

Problem: Didn't escape backslash

---

zproject_class_api.gsl

Soltion: Use the xml syntax from zproto to add uint8-64_t types

Problem: Cannot specify uint8-64_t types in class api

---

README.md
README.txt
zproject_bindings_jni.gsl
zproject_bindings_python.gsl
zproject_bindings_qml.gsl
zproject_bindings_ruby.gsl
zproject_class_api.gsl

Solution: Improve consistency and documentation of the models.

Problem: Bindings generator models are hard to understand.

---

zproject_known_projects.xml

Solution: add fuse, zdb, magpack definitions to zproject_known_projects.xml

Problem: absent definition of fuse, zdb, magpack in known projects list

---

zproject_automake.gsl

Solution: install the API files to share/zproject instead

Problem: none executable API files are installed into the bin directory

---

zproject_automake.gsl
zproject_class_api.gsl

Solution: Group API files by library and install them into sub-directories

Problem: API files are installed into the same directory

---

zproject_class_api.gsl

the same attribute is confusing. Also this breaks some bindings
Solution: Only use the variadic variable.

Problem: Having two variables (variadic, is_variadic) which represent

---

project.xml
src/Makemodule.am
zproject.gsl
zproject_bindings_qt.gsl

Solution: Copy the QML bindings and do a whole lot of changes ;)
Can be used as internal (with pri files) or external (installed on the
system) library or can be linked statically.

Problem: Need Qt bindings for my zproject

---

README.md
README.txt

Solution: Add them to the documentation

Problem: README is out of date, regarding the method and container parameters

---

zproject_class.gsl

Solution: fixed backslash escaping, syntax error and some minor style issues.

Problem: selftests won't compile

---

zproject_class.gsl

Solution: define argn beforehand.

Problem: declaration inside for loop is not standard C

---

zproject_bindings_qt.gsl

Solution: Correct the indentation

Problem: Indentation on generated Qt headers is wrong

---

zproject_bindings_python.gsl

solution: Use macro expansion to get correct index, as other code paths do

problem: Python bindings generation issue with > 1 argument before variadic

---

zproject_autoconf.gsl
zproject_automake.gsl

Solution: use C style format for make and shell variable names

Problem: can't build autotools project with hyphen in the name

---

README.md
README.txt

Solution: Explain how the new minimal setup works and how further steps
for user may look like.

Problem: Getting started information is not up to date

---

zproject_bindings_jni.gsl

Invoke javah from either maven or gradle

Fix #281 - Remove JNI header gsl code generator

---

zproject.gsl
zproject_spec.gsl

Solution: Generate one from zproto's project.xml
Note there are a few things around License, URL and Group, which should
be improved. But basically it works well

Problem: need to write spec file manually

---

zproject_spec.gsl

Solution: remove -n from devel package filelist, support explicit
values for License and URL tags from project.xml

Problem: generated spec file contains small issues

---

project.xml
src/Makemodule.am

Solution: Add them to the project.xml and re-generate zproject with zproject

Problem: New gsl scripts _debian and _spec are not installed

---

zproject_class.gsl

Solution: add :c mangling to generated macros

Problem: can't run make check on project with hyphen in the name

---

zproject_bindings_ruby.gsl

* correctly handle variadic arguments
* provide complete list of Ruby keywords

Improve Ruby bindings

---

zproject_automake.gsl
zproject_class.gsl

Solution: generate $(class.name)_selftest.cc for C++ projects

Problem: C++ projects do not support make check

---

zproject_bindings_ruby.gsl

Solution: Coerce it before returning it back to C.
This also improves some variable names.

Problem: callback result isn't coerced back for C

---

zproject_autoconf.gsl
zproject_automake.gsl

Solution: Add services parameter for mains that will generate service
file that can be run parametrized by configuration.

Problem: Want to have multiple instances of service

---

zproject_class.gsl
zproject_class_api.gsl

Solution: Make it add the description before the enum typedef.

Problem: C interface GSL skips enum description

---

zproject_class.gsl

Solution: When project is c++ based, generate .cc files.

Problem: .c files are generated in c++ project

---

zproject_automake.gsl

In detail, I have to modify it a little bit and my main doesn't require
any configuration file.
Solution: Not overwriting service file during generation and introducing
optional parameter to prevent config file from generating/installing.

Problem: Can't use generated service file

---

zproject_automake.gsl

Solution: Use :c variation of the name

Problem: Can't use dash in variable name in automake

---

zproject.gsl
zproject_automake.gsl

Solution: Not c-ifying filenames, just variables.

Problem: Can't use sources with dash in the name

---

zproject_class_api.gsl

Solution: added to mapping in zproject_class_api.gsl

Problem: zproject does not recognize ZMQ pollitem type

---

README.md
api/myclass.xml

Solution: remove those examples
In addition to #332

Problem: API examples describe removed exclude attribute

---

zproject_bindings_jni.gsl

Solution: add these (had to fix other errors in zproject first)

Problem: JNI generator can't handle format and number types

---

zproject_bindings_jni.gsl
zproject_class_api.gsl

Solution: default silently to 1 for types other than strings/buffers.

Problem: mutable property had wrong default

---

Makefile.am
README.md
README.txt
configure.ac
zproject_automake.gsl

Solution: Put them into a bullet list instead of a plain sentence.

Problem: The binding generation is no eye catcher

---

zproject_automake.gsl
zproject_bindings_jni.gsl
zproject_class_api.gsl

See commits for thorough details!

Fixed dependency handling

---

README.md
README.txt
api/myclass.xml

Solution: Change it to reflect the new mutable attibute and provide an
additional example method which uses it.

Problem: docs still mention the constant attribute

---

zproject_bindings_ruby.gsl

Solution: handle it as integers

Problem: Ruby binding handles uintX_t as pointer

---

zproject_bindings_jni.gsl

This is meant to be an internal mechanism.
Solution: don't have that in the API.

Problem: JNI method API should not show 'self'

---

README.md
README.txt

Solution: merge information from both lists into the first one

Problem: duplicate list of language bindings

---

zproject_bindings_jni.gsl

Solution: a lot of hacking on the JNI generator.

Problem: JNI API is not returning proper types

---

zproject_bindings_jni.gsl

Solution: collect dependencies which have their own API models.

Problem: JNI class does not import dependencies properly

---

zproject_spec.gsl

Solution: see commit messages below

Problem: generated spec not usable

---

zproject_debian.gsl

Solution: replace it by hyphen and fix generating of binary package
lists accordingly

Problem: Debian packaging disallow underscore in package name

---

zproject_spec.gsl

Solution: add suppost for tags bin, service and new parameter services
for main

Problem: filelist does not contains all installed files

---

zproject_bindings_jni.gsl

Problem: JNI backend cannot handle multiple constructors

---

zproject_class.gsl

See https://github.com/zeromq/czmq/pull/1227

Solution: swap order of statements

---

zproject_qt_android.gsl

Solution: echo "successful" at end

Problem: Qt Android build says nothing if successful

---

README.md
README.txt
zproject.gsl
zproject_bindings_qml.gsl
zproject_git.gsl

Problem: dangling references to qt-android

---

project.xml
src/Makemodule.am

Solution: learn to use egrep command

Problem: still more dangling references to qt-android

---

zproject_automake.gsl

Solution: do not do extra file name mangling

Problem: extra files are not properly added to Makemodule.am

---

zproject_bindings_qt.gsl

Solution: use zstr_free instead of free

Problem: c string is not freed properly in Qt binding

---

zproject_autoconf.gsl
zproject_bindings_python.gsl
zproject_known_projects.xml
zproject_projects.gsl
zproject_vs20xx.gsl
zproject_vs20xx_props.gsl

These were caused by my stripping-down of the previous set of
backends.
Solution: fixed.

Problem: numerous problems in Windows builds

---

zproject_known_projects.xml

See #409
Solution: interim workaround is to disable version checking.

Problem: version checks are not accurate

---

mkapi.py

Solution:
* support enums without values
* don't print void argument
* enhance zproject type mapping
* support const qualifier

Problem: can't generate czmq API model

---

.gitignore
CMakeLists.txt
zproject_cmake.gsl

Solution: only produce libraries etc. if project has classes.
Fixes #400

Problem: CMake build fails on empty project

---

zproject_bindings_jni.gsl
zproject_bindings_jni_vs20xx.gsl
zproject_cmake.gsl

Solution: only generate JNI tree if project needs it

Problem: generates JNI bindings when project has no classes

---

mkapi.py

Solution: create (class local) set of callback typedefs and store
information in xtra dictionary of ArgDecl

Problem: callback info not printed

---

mkapi.py

Solution: add a simple (and wrong) heuristic that fresh = "1" is printed each time non const pointer is returned.

Problem: generated API model don't support fresh

---

mkapi.py

Solution: print the comment before method informing about fresh

Problem: it's not easy to detect fresh attribute

---

mkapi.py

Solution: fix unecessary constant="1" and add off_t mapping

Problem: zdir.xml is not like original

---

mkapi.py

Solution: refactor code to mangle it for arguments and return type

Problem: enum type not properly mangled

---

mkapi.py

Solution: print self_p for non destructors

Problem: generated zframe_send does not look like original

---

mkapi.py

Solution: rename to mutable
TODO: current implementation maybe prints more mutable arguments, but
generated zchunk.xml does not change function prototypes, which is
great!

Problem: there is no constant argument attribute

---

zproject_ci.gsl

Solution: speed up compilation time by using `make -j4`

Problem: travis tests are taking too long

---

mkapi.py

Solution: add positional arguments behing include to specify the classes
to be generated

Problem: can't generate only one or a few classes at time

---

zproject_cmake.gsl

Solution: add lbiraries of found optional libraries to
OPTIONAL_LIBRARIES variable.
(See https://github.com/zeromq/czmq/pull/1298)

Problem: CMake uses libraries of non-found optional libraries

---

mkapi.py
zproject_class_api.gsl

Solution:
* fix comment aligment
* remove unamed arguments
* add clock type

Problem: can't generate zclock API model

---

zproject_autoconf.gsl
zproject_bindings_jni.gsl
zproject_class.gsl
zproject_cmake.gsl
zproject_known_projects.xml
zproject_projects.gsl

Solution as bunch of small changes. See commit message.

Problem: cannot build app using ALSA library

---

ci_build.sh

Solution: pass -target:* in ci_build.sh gsl run

Problem: Travis CI only builds default targets

---

mkapi.py

fixing what I come across as I try to use it for malamute

More small fixes to mkapi.py

---

zproject_autotools.gsl
zproject_debian.gsl
zproject_projects.gsl
zproject_redhat.gsl

Solution:
* correctly iterate through all extra's of main
* add attribute cond (condition) to distinguish files belong to
conditional installation or others
* fix redhat and debian packaging as well

Problem: can't have more extra files for one main

---

mkapi.py

Solution: ... see commits
The full command line is
```sh
mkapi.py -DWITH_DRAFTS -I /usr/share/python-pycparser/fake_libc_include/ include/globaldom.h gdom_client
```
-DWITH_DRAFTS because classes are hidden behind the macro and won't be found otherwise
fake_libs_include fixes all the ply/pycparser errors I found

Problem: can't generate API model for globdom

---

README.txt

Solution: enhance it a bit
https://github.com/zeromq/zproject/issues/478

Problem: mkapi documentation is not clear enough

---

zproject_class.gsl
zproject_class_api.gsl
zproject_python.gsl

The zproto headers one is the slightly more interesting one.

Two patches

---

Dockerfile

Solution: depend on zeromq/gsl
Problem #2: image cannot be used as utility
Solution: setup workdir

Problem: image does not depend on zeromqorg/gsl

---

README.md
README.txt

Solution: add this to README
Fixes #487

Problem: target syntax is not documented

---

zproject_travis.gsl

Problem: CI script should be executable

---

zproject_travis.gsl

Problem: generated .travis.yml shoudl request docker service

---

zproject_travis.gsl

Problem: wrong syntax for chmod_x

---

zproject_travis.gsl

Solution: change from git log -oneline to git log --oneline

Problem: typo in git log command in Travis CI

---

zproject_projects.gsl
zproject_travis.gsl

Solution: see individual commits

Problem: libsodium CI builds from master instead of stable

---

zproject_class.gsl

Problem: was adding extra blank lines after @end in interface

---

zproject_known_projects.xml
zproject_projects.gsl

Solution: resolve debian_name and spec_name from known use and add
proper debian_name for uuid

Problem: debian packaging broken after adding uuid dependency

---

zproject_autotools.gsl

Solution: install the .cfg file regardless

Problem: .cfg file is installed only when systemd is selected

---

zproject_nodejs.gsl

Solution: use project.topdir which seems to be the correct one

Problem: my.topdir variable is unkown

---

zproject_gyp.gsl
zproject_nodejs.gsl
zproject_travis.gsl
zproject_vs20xx.gsl

* Allow building dependencies from tarballs
* Execute buildconf instead of autogen.sh which is used e.g. by libcurl

Travis fixes

---

README.md
project.xml

Solution: explain the in the README

Problem: repository and tarball option for dependencies are not documented

---

CMakeLists.txt
README.md
README.txt
configure.ac
project.xml
zproject.gsl
zproject_nodejs.gsl
zproject_nuget.gsl

```
<target name = "nuget">
<option name = "id" value = "czmq_vc120" />
<option name = "platformtoolset" value = "v120" />
<option name = "dependency">
<item name = "libzmq_vc120" value = "4.2.0.0" />
</option>
</target>
```

Added target options

---

zproject_nodejs.gsl

Solution: add header that exports classes and methods.

Problem: node.js: can't use CZMQ from Zyre binding

---

README.md
README.txt

Solution: Link to chapter 3 of hintens book scalable c.

Problem: zproject has no step by step tutorial.

---

api/myclass.api

Problem: example class XML has syntax errors

---

zproject_skeletons.gsl

The generated code was generating tests that lock up selftest by default.
I am not sure yet what they should generate but probably not what they are.

remove test code and fix comment

---

zproject_skeletons.gsl

just remove testing code

---

zproject_known_projects.xml

problem: confused what test should be
solution: add to comment its equivalent from autoconf

Just add a comment

---

README.md
README.txt

Problem: Command missing ./

---

README.md
project.xml
zproject_class.gsl
zproject_projects.gsl
zproject_skeletons.gsl

In general negative names are difficult for users (they lead to
double negatives like 'notests is 0 by default').
Solution: use 'selftest' which defaults to 1 on actors and classes

Problem: 'notest' is a weak name for a property

---

zproject_class_api.gsl
zproject_projects.gsl

Solution: set selftest default in all generated classes.

Problem: zproject_class.gsl 190 Undefined expression

---

zproject_ruby.gsl

Solution: move them to the respective class.

Problem: constants are in wrong namespace in Ruby binding

---

zproject_nodejs.gsl

Solution: add this in all files as appropriate/possible

Problem: NodeJS generated files don't have warning header

---

zproject_nodejs.gsl

Solution: do this, in nodejs target

Problem: can't handle arguments with map values

---

zproject_nodejs.gsl

Solution: first time only generation

Problem: [nodejs] need to generate a skeleton index.js

---

zproject_class_api.gsl

Solution: Resolve APIs with api and xml extension.

Problem: [bindings] dependent APIs are only resolved with xml extension

---

README.txt

Problem: 'polymorphic' attribute isn't documented

---

zproject_travis.gsl

Problem: [travis] distcheck not used for draft build, insufficient cleanup between draft and non-draft test builds

---

Makefile.am

Solution: regenerate
It's turtles all the way down :-)

Problem: zproject out of sync with zproject

---

zproject_autotools.gsl

See commit messages for details!

autotools print summary and help

---

README.txt
zproject_autotools.gsl
zproject_debian.gsl
zproject_known_projects.xml
zproject_projects.gsl
zproject_redhat.gsl

Solution: clean them all + enhance documentation

Problem: there are several oddities introduced by myself into zproject

---

zproject_java.gsl

* Upgrade gradle from 2.8 to 2.13
* Upgrade gradle plugins
* Add bintray plugin to publish artifacts to jcenter repository

[jni] gradle upgrade & bintray publishing

---

zproject_autotools.gsl

Enable the compilation on msys2 mingw64 using autotools.

Add compilation with mingw64 using autotools

---

zproject_travis.gsl

Solution: only check out those repositories with a valid url

Problem: [travis] zproject check tries to checkout repository with no url

---

zproject_android.gsl
zproject_java.gsl

Problem: Android CI NDK version and ABI are outdated

---

zproject_java.gsl

Solution: add badge to jni README

Problem: [jni] user may not know about bintray deployment

---

zproject_git.gsl

Solution: Add them the .gitignore file

Problem: [git] valgrind files are not ignored by git

---

zproject_cmake.gsl

Solution: remove *.so, platfrom.h and *.pc files as well

Problem: [cmake] Cleaning source distribution missing files

---

zproject_cmake.gsl
zproject_travis.gsl

Solution: Adept the cmake ci script from czmq and enable it in new projects by default.

Problem: [cmake] no ci script is generated for cmake

---

zproject_cmake.gsl

Solution: add suppression file to command options instead

Problem: [cmake] suppression file setting is not respected

---

zproject_debian.gsl

Solution: Add project dsc and format files

Problem: [debian] packaging missing dsc and format required by OBS

---

zproject_redhat.gsl

Solution: fix deps and add missing

Problem: [redhat] wrong and missing deps for fedora  24

---

zproject_debian.gsl

Revert "Problem: [debian] packaging missing dsc and format required by OBS"

---

zproject_debian.gsl

Solution: Add it and print latest version
see #658

Problem: [debian] missing format file

---

.gitignore

Solution: Add '*~' pattern to .gitignore

Problem: editor backup files are not ignored

---

zproject_redhat.gsl

Solution: add zproject path as well.

Problem: [redhat] need to own all directories in a path for opensuse

---

zproject_obs.gsl

Problem: OBS service does not work with CentOS/RHEL

---

zproject_travis.gsl

Solution: if dependencies has both tarball and repository prefer tarball.

Problem: tarball and repository used  for testing

---

zproject_rpi.gsl

Solution: Use current working dir instead instead

Problem: [rpi] build script wrongly relies on personal home dir

---

zproject_debian.gsl
zproject_obs.gsl
zproject_redhat.gsl

Solution: see individual commits

Problem: various packaging issues

---

zproject_autotools.gsl
zproject_debian.gsl
zproject_obs.gsl
zproject_redhat.gsl

Problem: packaging issues, systemd service issues, make distclean does not clear docs

---

zproject_git.gsl

Solution: Add them to .gitignore file

Problem: [git] temporary qt files are not ignored

---

zproject_rpi.gsl

Problem: [rpi] Readme has typos

---

zproject_ruby.gsl

Compute env name from project.libname

---

AUTHORS

Solution: add it and add my employer, Brocade Communications Systems

Problem: AUTHORS file does not have Corporate snippet

---

AUTHORS

Solution: Match the format used by libzmq

Problem: AUTHORS format/wording for corporate contributors is unclear

---

CMakeLists.txt
configure.ac
zproject_known_projects.xml

Solution: change url to point to new repository

Problem: curl repository has changed

---

zproject_autotools.gsl

Solution: add a note to make summary

Problem: make coverage target not advertized

---

zproject_travis.gsl

Solution: Use generic project variable instead of czmq specific.

Problem: Deployment variable for jni is wrong

---

zproject_travis.gsl

Solution: Add the current version to the deployed android jar file.

Problem: Auto released android jar has no version

---

zproject_cmake.gsl

Solution: don't add private classes to the list as they will not be
visible externally

Problem: CMake runs tests individually from list of classes

---

configure.ac

Problem: zproject is out of date with zproject

---

zproject_autotools.gsl

Solution: if it exists add it to EXTRA_DIST files list

Problem: CMakeLists-local not included in release tarball

---

zproject_autotools.gsl

Solution: remove :c transformation for documentation  files

Problem: wrong docs if project starts with a number

---

zproject_travis.gsl

Solution: ... for projects starting with a number. Use :c ident

Problem: CI build has invalid variable names

---

README.md
zproject_known_projects.xml

Solution: change check zctx_test -> zhashx_test

Problem: cztx class in czmq is deprecated and removed

---

zproject_autotools.gsl

Solution: add @interface section to .c file and make mkman to correctly process it

Problem: Cannot add to the documentation some custom defined behaviour

---

zproject_autotools.gsl

Solution: Add them to same *_la_SOURCES list as the main C(CC) file

Problem: Generated *_engine.inc files are not EXTRA_DISTed for "make dist(check)"

---

zproject_known_projects.xml
zproject_travis.gsl

Solution: revise the list to always include the extension (less surprise in regenerated ci_build.sh scripts then); also fix imagix => imatix for GSL

Problem: known_projects listed some github upstreams without the .git extension

---

zproject_docker.gsl
zproject_vagrant.gsl

Solution: Except the .git suffix to be set by the repository
variable

Problem: Appending .git fails if repository already has suffix

---

zproject_debian.gsl

Solution: revert and add comments so next time I remember

Problem: I fix things, then forget about them and break them again

---

zproject_class_api.gsl

Solution: refactor code, look in workspace first, look in /usr/share/zproject last, and echo which file is being imported

Problem: class dependency resolution does not give priority to workspace and does not look in /usr/share

---

packaging/debian/control
zproject_debian.gsl
zproject_redhat.gsl

Problem: inconsistent descriptions of generated packages

---

zproject_autotools.gsl

Solution: use C names for source files and use real basename in mkman

Problem: make fails for project with - in name

---

zproject_autotools.gsl

Problem: mkman: messed up with sigils

---

zproject_autotools.gsl

Solution: use dist_bin_SCRIPTS for binaries
see https://www.gnu.org/software/automake/manual/html_node/Scripts.html

Problem: make distcheck failed

---

project.xml
zproject_travis.gsl

Solution: make distcheck opt-in

Problem: ci tests runs too long

---

src/Makemodule.am

Solution: make Makemodule.am consistent with a script

Problem: check_zproject fails

---

zproject_known_projects.xml

Problem: fty-proto is base library of 42ity project

---

README.md
zproject_travis.gsl

Solution: add a builddir to zproject use model

Problem: generated ci script does not work for tntdb

---

packaging/debian/zproject.install
packaging/redhat/zproject.spec
project.xml
src/Makemodule.am

Solution: add it and regenerate files

Problem: zproject_lua_ffi.gsl is missing from the Targets list

---

zproject_lua_ffi.gsl

Solution: add types from standard library and czmq_prelude to lua_ffi
generator

Problem: czmq lua bindings have undefined types

---

configure.ac
zproject_autotools.gsl

Problem: android build broken due to AC_CHECK_FILE

---

packaging/debian/rules
zproject_class_api.gsl
zproject_debian.gsl
zproject_travis.gsl

Note that the Ubuntu 12.04 (ie: for container builds) builds are still in progress, got some automake shenanigans to sort out. Everything is already building for 14.04 though (default on Travis)

Problems: API subdir check broken, pre-built packages not used on Travis

---

packaging/debian/control
packaging/redhat/zproject.spec
project.xml
zproject_debian.gsl
zproject_redhat.gsl
zproject_travis.gsl

Problems: cannot express package runtime dependency, zproject check CI does not use packages

---

builds/cmake/ci_build.sh
zproject_cmake.gsl

Solution: implement same solution for the other test and use packages
if they are available before cloning and rebuilding

Problem: travis cmake check does not use packages

---

README.md
configure.ac
project.xml
zproject_autotools.gsl
zproject_cmake.gsl

Fixes https://github.com/zeromq/zproject/issues/409
This implements what Pieter suggested in issue 409, and now there's an explicit settings for the ABI (that follows libtool's current:revision:age) to define in project.xml.

Problem: versioning is a mess

---

zproject_debian.gsl
zproject_redhat.gsl

Problem: library packages don't use the ABI version for the names

---

README.md
README.txt
project.xml
zproject_projects.gsl

Solution: Fix the typos (and hanging whitespaces, while at it)

Problem: Saw some typos while reading about known_projects.xml

---

zproject_cmake.gsl

Solution: Prot the code from one gsl script to another

Problem: cmake recipes not in sync with travis/autotools ones

---

builds/cmake/ci_build.sh
tstgenbld.sh

Solution: fix trailing `&&` to `&& \` etc.; always `exit $?` explicitly (not just on success) and comment why not drop it at all; double-quote echoed and argument strings; fix determination of `$finalresult`; mark the `initial cleanup` phase as such; use `mv -f` for log renaming; drop `test $? == 0` nonsense

Problem: tstgenbld.sh scripting style is unconventional and has logic errors

---

.travis.yml
ci_build.sh
zproject_cmake.gsl

Solutions: see commits
See https://github.com/zeromq/malamute/issues/98

Problems: Cmake does not install executables, zproject does not use prebuilt gsl

---

.travis.yml
ci_build.sh
zproject_cmake.gsl

Solution: fix variable quoting; fix use of PATH for local gsl; add ccache support to speed up CI respins (development competed with today's addition of packaged GSL for Linux though)

Problem: Improve scripting of ci_build.sh

---

builds/check_zproject/ci_build.sh
zproject_travis.gsl

Problem: scripts generated for Travis can be optimized and made more robust

---

doc/mkman
zproject_autotools.gsl

Problem: zproject tracked sources differ from what zproject currently generates for others

---

zproject_debian.gsl

Problem: comment in control file breaks BuildService parser

---

zproject_class.gsl

Partially fixes https://github.com/zeromq/zproject/issues/808

Problem: output of selftest -l is misleading

---

zproject_debian.gsl
zproject_redhat.gsl

Relax the glob for systemd unit types

---

zproject_debian.gsl

Solution: use the same number as project version

Problem: wrong name of install file

---

zproject_debian.gsl

Forgot to fix the control file when I updated the install file generation, thanks @vyskocilm for spotting my mistake

Problem: Debian lib package name in control file does not follow policy

---

README.md
README.txt

Solution: add a paragraph in the README
Fixes https://github.com/zeromq/zproject/issues/773

Problem: license of generated sources not explicitly stated in README

---

packaging/debian/control
packaging/debian/zproject.dsc.obs
zproject_debian.gsl

Problem: asciidoc has a lot of dependencies and it's in the wrong section

---

zproject_cmake.gsl

Solution: there is always time for a first attempt to write CMake syntax code ;)
Sibling to #826 
Note: testing with a real cmake project needed, no idea if I got the syntax to compare result code right

Problem: want cmake to find git workspace root in higher level directories

---

zproject_install.gsl

Problem: debug print left in zproject_install

---

configure.ac
zproject_autotools.gsl

And these are just steps on a path to solving a larger problem ;)

Steps to solve Issue #567

---

zproject_class.gsl

Problem: unescapted \n breaks selftest build

---

zproject_autotools.gsl

Solution: only set it for private ones

Problem: private flag is set for all models

---

.travis.yml
zproject_travis.gsl

Problems: Travis can be further optimized

---

zproject_known_projects.xml

Problem: fastjson and lognorm missing repo info

---

AUTHORS
zproject_debian.gsl
zproject_redhat.gsl

Solution: Add snippets for bin programs too

Problem: Only main is considered for systemd

---

zproject_systemd.gsl

Solution: Remove the line which has been added by accident

Problem: Copy and paste error in systemd redhat spec

---

.gitignore
zproject_autotools.gsl
zproject_git.gsl

Solution: My guess at how to fix it, real review is desirable :)
@sappo : you seem to have latest git-blame hits in this area, plz take a look before just merging :)

Problem: Generated Makefile had strange rules for src: and code:

---

src/Makemodule.am

So red travis was not only due to AWS S3 issues... :)

Regenerated src/Makemodule.am with correct template

---

.travis.yml
zproject_travis.gsl

Solution: switch to shiny new one in the network:messaging namespace

Problem: Travis using deprecated OBS project

---

.travis.yml
ci_build.sh
src/Makemodule-local.am
src/zproject_selftest

Finish the old quest to provide some reasonable placeholders for make check and make distcheck in the fashion dictated by zproject itself, so these recipes succeed and do some non-trivial job.

Problem: zproject make check and distcheck are incomplete

---

README.md
project.xml

Problem: "travis_distcheck" option documented as "distcheck"

---

zproject_autotools.gsl

Problem: extra blank line added in autogen.sh

---

zproject_cmake.gsl

soluction : enable zproject based libraries to detect windows UWP in CmakeLists.txt

problem : windows uwp platform not handled

---

zproject_travis.gsl

zproject_travis.gsl : harmless but pedantic typo fix

---

packaging/obs/_service
zproject_obs.gsl
zproject_travis.gsl

Problem: OBS _service could use some update

---

zproject_python_cffi.gsl

Solution: add setup.py, improve docs ...
sorry @sappo you've been too slow ;-)

Problem: python_cffi bindings lacks standard build/install way

---

zproject_python_cffi.gsl

Solution: change exec, and use proper types, so build can run with python3 too

Problem: python_cffi not python3 compatible

---

packaging/debian/control
packaging/debian/copyright
packaging/debian/rules
zproject_debian.gsl
zproject_python_cffi.gsl
zproject_redhat.gsl

Problem: no Debian Python CFFI packages, Lintian warnings, etc

---

zproject_debian.gsl

Problem: missing escape breaks generation

---

packaging/debian/control
packaging/debian/rules
zproject_debian.gsl

Problem: no support for Debian build profiles and nodoc/nopython options

---

zproject_autotools.gsl

HI,
here is the pull request for (https://github.com/zeromq/czmq/pull/1694)
BR Frank :-)

fixed Werror messages building on mingw32 mingw64

---

zproject_debian.gsl
zproject_redhat.gsl

Solution: use project.name / project.libname

Problem: czmq hardocded in debian/redhat packaging scripts

---

configure.ac
zproject_autotools.gsl

Problem: indentation, out of date

---

zproject_debian.gsl

Solution: give it the relative path to the build directory instead

Problem: dh_installman fails with install path

---

zproject_redhat.gsl

Problem: some minor issues with spec file

---

zproject_cmake.gsl

Cmake and src/selftest-r{o,w} directories

---

.travis.yml
CMakeLists.txt
zproject_travis.gsl

Problem: Ubuntu 12.04 is EOL and Travis is moving away

---

Makefile.am
packaging/debian/control
packaging/debian/copyright
packaging/redhat/zproject.spec
zproject_debian.gsl
zproject_travis.gsl

Solutions: don't install binutils, regen

Problems: OSX Travis builds are too slow, out of date with GSL, Debian copyright malformed

---

.travis.yml
builds/check_zproject/ci_build.sh

Solution: go from docker to packages
Addresses issue #952

Problem: old gsl used to selftest zproject

---

packaging/debian/control
zproject_debian.gsl

Solution: update package generation and regen

Problem: out of date with Debian Policy 4.0.1.0

---

zproject_debian.gsl
zproject_known_projects.xml
zproject_redhat.gsl
zproject_travis.gsl

Problems: optional build-deps added to package builds but not enabled, CI installs optional deps but does not enable them, no LZ4 in known_projects

---

zproject_python_cffi.gsl

Solution: Pass cdata pointer instead of wrapping python object

Problem: void * arguments get python object instead of cdata pointer

---

.editorconfig
zproject_git.gsl

Solution: port the file from malamute to seed in other zprojects

Problem: .editorconfig is missing

---

zproject_valgrind.gsl

Solution: ignore init calls of libgcrypt

Problem: memory leaks from indirect libgrypt dependency

---

zproject_class_api.gsl

Solution: test for this flag in zproject_class_api.gsl

Problem: selftest=0 still makes header declarations

---

zproject_class_api.gsl

Solution: default it if absent
Hope this solves the recent breakage, but testing is desired.

Problem: class selftest option may be not defined

---

AUTHORS
README.md
zproject_jenkins.gsl

Solution: Add jenkins target to create nice working pipeline file.

Problem: To start with jenkins pipeline is hard

---

zproject_known_projects.xml

Solution: change url to zeromq organization

Problem: gsl points to old imatix namespace

---

builds/cmake/ci_build.sh

Solution: re-generate zproject
See #974

Problem: zproject not regenerated after gsl location change

---

Jenkinsfile
README.md
project.xml
zproject_jenkins.gsl

Solution: add the option similarly to Travis recipe; fix and mark a few nearby issues in this area

Problem: Jenkinsfile does not "make distcheck"

---

Jenkinsfile
zproject_jenkins.gsl

Problem: Jenkins pipeline - timeout units must be quoted

---

builds/cmake/ci_build.sh
configure.ac
zproject_autotools.gsl

Solution: call AC_C_BIGENDIAN for autotools to determine the endianess of the
system. This defines WORDS_BIGENDIAN macro on big endian systems.

Problem: need to branch the code according system endianess

---

zproject_redhat.gsl

Solution: retrieve it from pkgconfig instead to fix builds on CentOS 6

Problem: spec file uses hard-coded systemd unit path

---

zproject_python_cffi.gsl

Solution; see commit messages for extensive documentation

Problem: usability problems of generated python cffi

---

zproject_nodejs.gsl

Otherwise the internal utf8 storage will delete the buffer before it is used

Remove scope around the use of utf8 converters 

---

zproject_redhat.gsl

Solution: do not generate empty line in spec file

Problem: CI for zproject fails

---

zproject_python_cffi.gsl

Solution: use dynamic binding
cc @sappo

 Problem: can't mix two FFI bindings together 

---

zproject_python_cffi.gsl

Thanks @vyskocilm for help.
SOLUTION: Fix it.

PROBLEM: binding crashing

---

README.md
project.xml
zproject_jenkins.gsl

Solution: Make the default value configurable via project.xml options and document this

Problem: Jenkinsfile SCM polling is set in stone

---

Jenkinsfile
README.md
project.xml
zproject_jenkins.gsl

Solution: Add an optional stage to make sure the built project is installable into a specified DESTDIR, and document it

Problem: Jenkinsfile does not test "make install"

---

Jenkinsfile
src/Makemodule.am
zproject_autotools.gsl
zproject_jenkins.gsl

Solution: bring them back for this usecase

 Problem: copying of selftest-ro for distcheck broken without abs_* vars

---

zproject_redhat.gsl

PROBLEM: Required version for python cffi bind

---

zproject_git.gsl

Problem: not-regen of .editorconfig claims .gitattributes

---

zproject_cmake.gsl

Signed-off-by: barraudl <lilianbarraud@eaton.com>

Add .cc files to the CMakeLists.txt

---

Jenkinsfile
Jenkinsfile-deploy.example
README.md
project.xml
src/Makemodule.am
zproject_autotools.gsl
zproject_jenkins.gsl

Based on experience from the past few weeks of intensive evolution and testing of the resulting scripts and what needed to be amended here and there...
Notable TODO: ensure prerequisites like in Travis, but more flexibly (any target OS is possible, not just Ubuntu with apt/dpkg).

Multiple nuance fixes to Jenkinsfile support

---

CMakeLists.txt
zproject_cmake.gsl

Problems: CMake builds everything twice, uses wrong static lib name

---

zproject_class_api.gsl

Solution: Rename the file to match to actual one.

Problem: Python slurp of dependency points to the wrong file

---

README.md
zproject_class.gsl
zproject_skeletons.gsl

Signed-off-by: barraudl <lilianbarraud@eaton.com>

Problem: #define format is not consistant

---

zproject_class.gsl
zproject_skeletons.gsl

Solution: Just use the colon to tell gsl to print c_name as is and
not apply any pretty printers

Problem: Pretty print suffix on c_name is obsolete

---

zproject_cmake.gsl

Fix multiples issues introduce with the last modifications of cmake file generation

Cmake Fixes

---

zproject_autotools.gsl

Solution: drop :c mangling in doc/Makefile.am as well

Problem: man1 pages are not built

---

zproject_class.gsl
zproject_class_api.gsl
zproject_skeletons.gsl

Signed-off-by: barraudl <lilianbarraud@eaton.com>

Problem: c_name was no longer :c formated. #include must inc name and not c_name

---

zproject_class.gsl

Problem: minor inconsistencies in test listing

---

.gitignore
builds/cmake/ci_build.sh
zproject_class.gsl
zproject_cmake.gsl
zproject_git.gsl

Problem: stable, cmake and osx builds broken

---

zproject_class.gsl
zproject_travis.gsl

Typo in travis message; Fix to selftest sentinel

---

zproject_autotools.gsl
zproject_travis.gsl

Have the ecosystem start with common reasonable settings (and/or evolve this set of settings to be reasonable).

zproject_autotools.gsl : provide a default .clang-format file

---

Jenkinsfile
README.md
license.xml
project.xml
src/Makemodule.am
zproject_autotools.gsl
zproject_debian.gsl
zproject_jenkins.gsl
zproject_travis.gsl

Also fix the starting_year from #1071 comments

Refactor the clang-format-check-CI to use in both CI recipes

---

zproject_python_cffi.gsl

Problem: API model comments not in python code

---

CMakeLists.txt
Makefile.am
builds/cmake/ci_build.sh
zproject_autotools.gsl
zproject_cmake.gsl

Solutions: include CMake clang files, run tests from tarball to catch regressions, fix errors
Fixes https://github.com/zeromq/czmq/issues/1882

Problems: CMake does not work with dist tarball, syntax errors

---

zproject_valgrind.gsl

Problem: memory errors from libgrypt init code with libgrypt 2.20.0

---

zproject_python_cffi.gsl

Problem: debug print left in zproject output

---

zproject_vs20xx.gsl

Works with VS2017 Community, I used it successfully to build czmq and zyre on my machine.

Added support for building Visual Studio 2017 environment

---

zproject_python.gsl

Solution:  comment away the private method

Problem: the python_gsl method_annotation include private functions

---

builds/cmake/Modules/ClangFormat.cmake
builds/cmake/ci_build.sh
builds/cmake/clang-format-check.sh.in
zproject_cmake.gsl

Trial with fire in https://github.com/zeromq/zyre/pull/601

zproject_cmake.gsl : use same settings as autotools for clang-format

---

README.md
project.xml
zproject_travis.gsl

Solution: add an option to the project.xml tag similar to the one for setting the Jenkins default.

Problem: CI_REQUIRE_GOOD_GITIGNORE=false hardcoded for travis default

---

README.txt
project.xml

problem: README.md have been edited manually.
solution: edit project.xml and README.txt to generate README.md

README.md have been edited manually

---

zproject_java.gsl

problem: many methods have to be static
solution: fix java bindig generator

Java Binding: many methods have to be static

---

CMakeLists.txt
zproject_cmake.gsl

Solution: use them for static linking

Problem: cmake does not use static pkg-config variables

---

zproject_delphi.gsl

solution: remove var modifier and use a pointer type instead.

problem: [DELPHI] zsys_handler_set function parametter is not nullable.

---

zproject_travis.gsl

Problems: OBS release trigger broken, no ABI check on Travis

---

zproject_known_projects.xml

Problem: libmicrohttpd is not in known projects

---

README.md

Somebody must have merged a red PR, oh my.

README.md : update with libmicrohttpd reference

---

zproject_projects.gsl

Solution: Copy the actor state field to class

Problem: actor state field is not copied to class

---

zproject_java.gsl

Solution: when tarball present don't build from repo

Problem: java try to build from repo when tarball present

---

Dockerfile

Problem: /tmp/zproject not cleaned up in Docker image

---

zproject_class.gsl

Solution: define the class structures before including the private headers

Problem: private headers cannot use project class structures

---

zproject_python_cffi.gsl

Solution: 
* add static decoration for singletons
* add variadics support
* add support for non default constructors

Problem: python_cffi is missing singletons, variadics and constructors

---

.travis.yml

Solution: update repository urls, switch jdk-7 to jdk-8

Problem: travis fail due to switch to ubuntu 16.04

---

zproject_python_cffi.gsl

Problem: a debug echo was left behind

---

zproject_autotools.gsl
zproject_travis.gsl

Unfortunately, Travis has an outage today (lost github hooks) as I was developing this, so it is not quite fully tested.

A few fixes to recently added travis dist and shadow compile supports

---

README.md
zproject_known_projects.xml

Problem: nss not defined in known_projects

---

zproject_redhat.gsl

Solution: do common steps only once

Problem: CFFI RPM builds with both python 2 and 3 broken

---

zproject_java.gsl
zproject_travis.gsl

Solution: Adjust the scripts accordingly
Also build JNI android build for all supported architectures.

Problem: Android build adjustments cause JNI android build to fail

---

zproject_java.gsl

Solution: Instead us project specific references

Problem: zproject_java.gsl contains czmq specific references

---

zproject_java.gsl

Solution: Don't deploy SNAPSHOTs

Problem: SNAPSHOT are deployed as release

---

zproject_android.gsl
zproject_java.gsl

Solution: Upgrade to version r21 which is the most current

Problem: Currently used android NDK r20 is unsupported

---

zproject_travis.gsl

Solution: Remove the exclamation mark

Problem: Check for empty BINDING_OPTS does the opposite

---

zproject_travis.gsl

Solution: Tell gradle not to start its daemon

Problem: travis windows build fails due to running gradle daemon

---

Dockerfile
packaging/docker/run_zproject.sh

Solution: Write a script that can be called when docker runs the image

Problem: Dockerfile has no proper entrypoint

---

zproject_cmake.gsl
zproject_travis.gsl

Solution: Use travis fold instruction to fold section in the log

Problem: travis logs are very verbose

---

builds/cmake/ci_build.sh
zproject_cmake.gsl
zproject_travis.gsl

Due to wrong parenthesis the second expression is wrongly evaluated
Solution: Set the parenthesis around the whole expression before negating it

Problem: CI test if package is installed is broken

---

CMakeLists.txt
README.md
packaging/debian/zproject.install
packaging/redhat/zproject.spec
project.xml
src/Makemodule.am
zproject.gsl
zproject_autotools.gsl
zproject_cmake.gsl
zproject_cucumber.gsl
zproject_known_projects.xml
zproject_travis.gsl

Solution: Add a new cucumber target that integrates zproject with cucumber-c

Problem: zproject has no integration with cucumber

---

zproject_android.gsl

Solution: Instead of check for defined check the actual value

Problem: android checks fail due to new default value for implied

---

zproject_android.gsl
zproject_java.gsl

Solution: Update gradle wrapper. Update and unify android NDK version.

Problem: Outdated dependencies

---

zproject_android.gsl

Solution: Update the android gsl to add the location from android ndk while looking for readelf binary.

Problem: Issue with generated android build script.

---

zproject_java.gsl

Solution: Updated the java generator to address the cmake related issues, while building jni bindings.

Problem: Zyre travis jni bindings build is failing.

---

zproject_android.gsl
zproject_java.gsl

Solution: Update NDK, gradle wrapper, gradle plugins and project dependencies

Problem: Outdated Android build tools

---

zproject_travis.gsl

Problem: JDK version in CI needs to match exported version

---

zproject_vs20xx.gsl

Tested locally: ok with a basic project.

Adding MSVC 2019 support.

---

zproject_java.gsl

Solution: Prepare to migrate to Gradle 7

Problem: Android and Java builds are stuck with Gradle 6.9

---

zproject_android.gsl
zproject_java.gsl

Solution: Fix Android build scripts to work with latest NDK version

Problem: Android NDK r25 is not supported

---

zproject_android.gsl

This change only requires the 2 other proposed fixes.

Problem: Android build scripts silently fail.

---

README.md
README.txt
zproject_known_projects.xml

Solution: Fix some (maybe not all) typos.

Problem: Documentation has some typos

---

zproject_gh_actions.gsl

force 20.04 as 22.04 is broken with unwind deps

gh actions have switched to ubuntu 22.04 

---

zproject_gh_actions.gsl

Solution: add libtool to brew install as MacOS 14 runner images don't have it installed

Problem: MacOS-14 gh runner scripts don't work

---

zproject_java.gsl

Solution: Update Gradle version 7.5.1 -> 8.9 and update project configuration accordingly

Problem: Java build run on outdated Gradle version

---

zproject_java.gsl

Solution: Use up to date tools and default XML lib by excluding Xerces

Problem: Java build fail with Gradle > 8.4

---

zproject_java.gsl

Problem: Java Gradle scripts should use task configuration avoidance API

---

zproject_java.gsl

Problem: Last second code cleanup led to use of non existing syntax

---

zproject_cmake.gsl
zproject_java.gsl

Originally from: https://github.com/zeromq/czmq/pull/2310
I cannot follow the generation instructions and I do not want to install autoconf and various dependencies on my system. If someone can do the generation, otherwise I will do those manually as a best guess effort

Allow building with CMake 4.0 and use GNUInstalldirs
