zeromq/zproject

- zproject_bindings_qml.gsl
- zproject_qt_android.gsl
Solution: accept ANDROID_BUILD_CLEAN env var to remove cached build prefix
> Problem: qt-android builds' caching can make outdated builds

- zproject_bindings_qml.gsl
Solution: Give a new name to the bindings project
> Problem: Confusing names for multiple QT creator projects in one repository

- zproject_bindings_ruby.gsl
Solution: Convert NULL pointers to nil so that they're easier to test for.
> Problem: Ruby wrapper objects might be given a NULL pointer on creation.

- zproject_docs.gsl
- zproject_mkman
The initial call of zproject_mkman generates incomplete man pages
which then fail with this error in asciidoc. The workaround is to
regenerate all man pages using zproject_mkman. This is not clean
nor obvious.
Solution: add "clean" target that removes .1 and .3 pages and
regenerates .txt and .doc files from source.
Fixes #131
> Problem: asciidoc: FAILED: manpage document title is mandatory

- zproject_autoconf.gsl
The second autoreconf step doesn't report back the correct exit code as
the test overrides it.
The output error mentioned error in #138 from the `autogen.sh` script is cause by this part:
```
autoreconf --install --force --verbose -I config
if [ $? -ne 0 ]; then
echo "autogen.sh: error: autoreconf exited with status $?" 1>&2
exit 1
fi
```
The `if [` part overrides the `$?` variable and so the echoed message contains always 0, which is misleading.
> Problem: autogen.sh: reported exit code wrong

- zproject_automake.gsl
Solution: Add an optional project-local automake script which can
perform the necessary checks and changes
> Problem: CZMQ has special link dependencies for some platforms

- zproject_autoconf.gsl
- zproject_automake.gsl
Solution: Manually include libstdc++ in the link line if shared libaries are not enabled
re https://github.com/zeromq/czmq/issues/927
> Problem: When configured with `--disable-shared` executables will not link

- zproject_class.gsl
Solution: Don't write a project header if a class has the same name.
Solution: Force a save of the class header so the @interface rewrite can happen.
This happened to me when creating a single class with API for the first time in a new project.
> Problem: Generating classes for the first time with API defined failed.

- zproject_bindings_python.gsl
Python-only changes, this makes zproject require the latest gsl, due to the slightly crazy string.replace function in gsl.
This also changes the format for the `use` directive - including class elements within that now cause the python bindings only to reference that external projects classes.
Note this change to `use` should probably be made either a requirement for referring to classes, or at least more widely used in other bindings.
> Python binding fixes and cross-project class referencing

- zproject_bindings_python.gsl
Solution: Only use classes which we generate or have been imported
> Problem: Python bindings using nonexistent classes

- README.md
- zproject_class.gsl
When the C language class header is initially generated, it includes method declarations for {class}_print() and {class}_test.  When the class api (api/{class}.xml} is subsequently created or updated, the method declarations for test and print are erroneously stripped.
README steps for installation of zproject were inaccurate.
> Fixes for inconsistencies in C class header regeneration and README for installation and use.

- zproject_class.gsl
- zproject_class_api.gsl
Solution: Use c_method_declaration to generate both header and implementation signature, with a parameter to choose which style
> Problem: First-run generated class has inconsistent whitespace

- zproject_automake.gsl
We moved to calculating project.libname some time ago, to allow
library name to be based off project prefix (e.g. mlm) instead of
full project name (czmq, zyre).
Solution: use $(project.libname) consistently.
> Problem: use of invalid "lib$(project.name)" construction

- zproject_class_api.gsl
Solution: Respect the `exclude = "1"` attribute in method and *structor models
Breaks/Replaces: use of the `has_print = "0"` attribute in class models
Solution comes from discussion in issue #156
> Problem: No consistent way to exclude implicit methods and *structors

- zproject_class.gsl
The generation of include guards did not fit to [the expected naming convention of the C++ language standard](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.").
This implementation detail can be fixed by deletion of [a few underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
> Fix include guards.

- zproject_class_api.gsl
Solution: clarify the subject of the sentence with the word 'object'.
Rationalle: In Zyre, this said "Print properties of the zyre", which
doesn't scan. "Print properties of the zyre object" works.
> Problem: Documentation for print method sounds odd.

- zproject_cmake.gsl
[A wiki article pointed out](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.") that whitespace will only be preserved for parameters in CMake commands if passed strings will be appropriately quoted or escaped.
Quoting can be added so that more places should also handle file names correctly which contain semicolons eventually.
> Complete quoting for parameters of some CMake commands.

- zproject_cmake.gsl
This is useful if the project is integrated in another CMake project
using add_subdirectory().  The libary type (STATIC/SHARED) can be
controlled from the master CMakeFile or from the command line
(-DBUILD_SHARED_LIBS).
This commit removes the explicit 'SHARED' type parameter.  If no type is
given explicitly the type is STATIC or SHARED based on whether the
current value of the variable BUILD_SHARED_LIBS is ON. [1]
[1] http://www.cmake.org/cmake/help/v3.0/command/add_library.html
If BUILD_SHARED_LIBS is not specified shared library is build by default.
> Use BUILD_SHARED_LIBS to specify the library type.

- zproject_bindings_python.gsl
Solution: Use the correct search term (you're not meant to include the
lib prefix when using find_library)
> Problem: Python bindings unable to find libc.

- zproject_bindings_python.gsl
Solution: Use the dynamic linker to do the initial search, this works on MacOS X and Linux, at least.
> Problem: Python bindings did not find libraries in a cross-platform way.

- zproject_automake.gsl
Solution: Add a check-local target which executes when make check runs,
and shows output correctly, even with the parallel test runner is active
(in newer autotools versions)
> Problem: automake tests run in parallel mode don't show output

- zproject_cmake.gsl
Solution: use project.prefix instead of project.name when building
a library filename.
> Problem: CMake generation does not use project.prefix consistently

- zproject_automake.gsl
Whereas this is done everywhere else. Result is that 'make dist'
fails.
Solution: use /src for these paths.
> Problem: EXTRA_DIST does not use 'src/' for extras

- zproject_docs.gsl
Solution: install man pages irrespective of BUILD_DOC setting.
Note: fix was made in libzmq already.
> Problem: does not install man pages if BUILD_DOC is off

- zproject_autoconf.gsl
zproject_autoconf.gsl has a check for the libtool binary as a mean to
check if libtool is available. But distributions like Debian and
Ubuntu are splitting the libtool package, and the libtool binary is now
in a separate package. What autoconf actually need is not the libtool
binary, but libtoolize and other macro files. So check for libtoolize
instead.
See package content for Debian, Ubuntu and Fedora:
https://packages.debian.org/jessie/amd64/libtool/filelist
http://packages.ubuntu.com/utopic/all/libtool/filelist
https://apps.fedoraproject.org/packages/libtool/contents/
As you can see, Ubuntu and Debian no longer ship the libtool binary inside the libtool package. Fedora still does. All of them, however, ship the libtoolize binary and the macro files, which is what autoconf actually …
> Check for libtoolize instead of libtool

- zproject_autoconf.gsl
Commit 6a5bafe1 changed the autogen.sh check from libtool to libtoolize
to accomodate changes in Debian and Ubuntu. But OSX does the opposite,
so we have to check for libtool. To accomodate both, check first for
libtoolize and then for libtool, and fail only if neither can be found.
> Fix checking for libtool on OSX

- zproject_autoconf.gsl
- zproject_cmake.gsl
Add project-local hooks for CMake and autoconf, following the model already set by the automake project-local hooks.
Will be used to fix issue #199.
> Autoconf and CMake project-local hooks

- zproject_autoconf.gsl
Sorry, I noticed a whitespace discrepancy a few seconds too late.
This commit will make sure that after ./generate.sh is run, if a project does not define local hooks then there is absolutely no change. Otherwise, an empty new line would be added to configure.ac
> Avoid whitespace change without local hooks

- zproject_bindings_ruby.gsl
External Libs had to call #__ptr where a FFI function is expecting a pointer, #to_ptr is the way to tell FFI this Object is convertible to a FFI pointer
> Problem: external Ruby Libs had to call #__ptr to get the underlying pointer

- zproject_bindings_ruby.gsl
Solution: Append an underscore when encountering these.
Relates to https://github.com/zeromq/czmq/issues/1062
> Problem: Ruby bindings can clash with self and alias keywords.

- zproject_ci.gsl
Hello,
As discussed in https://github.com/zeromq/libzmq/pull/1529 here's a PR to switch from VM to container based Travis CI builds. Needed changes were removing "sudo" and installing in local directory rather than in the default /usr/local.
Also -x is set in ci_build.sh, since it prints the executed commands to the log, which is very helpful when debugging.
> Enable container-based build

- zproject_ci.gsl
OSX does not ship with binutils, need to install it before the script
run via brew in order to be able to use greadelf, needed by the
qt-android CI script.
#209 introduced OSX build in the generated project, but since the qt-android build is present greadelf is needed by default as well.
> CI run on OSX needs binutils

- zproject_autoconf.gsl
This breaks apps that need it (mainly CZMQ). Solution: add library
check for libuuid, using uuid_generate. This works on Linux and OS/X
though not on xBSD, which uses uuid_create. No solution for that at
present.
> Problem: HAVE_LIBUUID never defined

- zproject_autoconf.gsl
- zproject_class.gsl
Solution: Don't throw an error if a optional library wasn't found and set a HAVE_$(LIB_LINKNAME) define if it was found. This permits to check for the library when platform.h is included in the source.
> Problem: zproject cannot handle optional libraries

- zproject_cmake.gsl
- zproject_qt_android.gsl
Solutions: exclude optional dependencies entirely
Someone with the proper knowledge about these build systems must find a better Solution
> Problem: cmake and qt android handle optional dependencies as required ones

- zproject_automake.gsl
the '-Werror=format-security' isn't set by default on all systems.
Solution: Add it to have a consistent compiling process.
> Problem: The compiling process is inconsistent on different system as

- zproject_class_api.gsl
Solution: Parse the api files for foreign data types and try to find the
installed api files from the dependent project.
This way, e.g. bindings for zyre can load the necessary api files from czmq
for the data types used in the zyre api. The class api for dependencies is
loaded to: project.dependencies.class and contains the same attributes
as: project.class.
> Problem: Bindings of a zproject that uses another zproject needs the dependent projects data types resolved.

- zproject_class_api.gsl
Solution: Add char as possible type
> Problem: ztrie uses a char in its API to pass a delimiter which is not supported by zproject's API

- zproject_autoconf.gsl
- zproject_automake.gsl
- zproject_known_projects.xml
Solution: use c-style
This problem also revealed that the project name for the libzmq project is wrongfully zmq which causes troubles with pkg_config_modules as a 'lib' prefix is automatically attached to cater this. The naming issue has been fixed as well.
> Problem: libaries with a '-' in in its name will cause autogen.sh to fail

- zproject_known_projects.xml
Solution: Add liblognorm and it's json-c dependency to zproject.
> Problem: I would like to use liblognorm with zproject

- zproject_class_api.gsl
Whereas the type 'format' implies a varadic attribute and automatically adds a
new varadic argument, other types have to add the varadic argument themselves which
is really unintuitive as it only defines the varadic attribute.
Solution: Instead of adding a new argument with only the varadic
attribute set. Add the varadic attribute to the last argument of the
function.
> Problem: API for defining varadic methods is unintuitive and inconsistent.

- zproject_autoconf.gsl
- zproject_known_projects.xml
- zproject_projects.gsl
This is not necessarily the case for other libraries.
Solution: Define the libname attribute for zproject based projects. Also
renamed sodium to libsodium and curl to libcurl and set prefix
accordingly.
> Problem: The libname for all zproject based projects starts with "lib".

- zproject_projects.gsl
Solution: Use project name as libname instead of prefix
> Problem: Most projects use project name as libname, not the prefix.

- zproject_class_api.gsl
Language bindings usually will exclude those methods except if there is
a sibling methods that supports a va_list.
Solution: Add an attribute to the method to indicate whether it has a
sibling method that supports a va_list.
> Problem: Perfect forwarding is oftentimes not supported for variadic methods.

- zproject_bindings_qt.gsl
Solution: Add another backslash to force line break and change if to
take dependencies into account.
> Problem: qt src pri file HEADERS and SOURCES are generated unformatted

- zproject_class.gsl
- zproject_cmake.gsl
Changes introduces with these commits:
- The FindXXX.cmake files did not work on Windows (due to lack of pkg-config).
So work around that.
- The selftest generator is rather simplistic. It is only possible to run them all.
So add an argument to select one test.
**IMPORTANT**
I do not know how to run gsl on the project.
__So these commits are written without any test.__
Please review these changes carefully (@sappo).
Referenced issue; zeromq/czmq#1131
> CMake: let findXXX.cmake work on Windows + make selftests smarter

- zproject_class.gsl
- empty function argument lists (use 'void')
- use of variables like i, p, etc. (formally disallowed)
- inline declarations in for loops (not standard C)
- action in for loops (move to body, it's cleaner)
- incorrect use of parenthesis (place opening { with statement)
- use of preincrement in for loops (why? we don't do that anywhere else)
Solution: fix these
> Problem: code for test command line has issues

- zproject_cmake.gsl
Problem: the cmake generator does not create the class selftest
Solution: add it
Problem: the find_packages of cmake contains non-matching if and endif
Solution: make them matching
> Fixes for autogenerated cmake

- zproject_bindings_python.gsl
Bindings generated for projects that use the buffered I/O (FILE*) C
library calls, e.g. "czmq", will not run on the version 3 of the
interpreter. The actual problem is that the API used to cast files from
Python to C, and vice-versa, is not available on this version. See
https://docs.python.org/3/c-api/file.html
Solution: update the GSL script to use the Standard C library functions
on Python 3.
> Problem: generated bindings failing on Python 3.

- zproject_bindings_python.gsl
As mentioned on the ML by Johan Philips the Python constructor can have wrong arguments:
```
from czmq import Zpoller
from zyre import Zyre
node = Zyre("test")
node.start()
poller = Zpoller(node.socket(), None)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/jphilips/workspace/czmq/bindings/python/czmq.py [czmq.py]", line 
1782, in __init__
self._as_parameter_ = lib.zpoller_new(args[0], *args[index()-1:]) # 
Creation of new raw type
NameError: global name 'index' is not defined
```
This PR request removes the undefined index() method.
After merge the bindings of projects might need regeneration.
> minor fix to the generation of python constructors

- zproject_bindings_python.gsl
Solution: Handle variadic arguments as 0 or more, rather that 1 arg
> Problem: Python bindings argument checking fails for variadic args

- zproject_autoconf.gsl
- zproject_automake.gsl
Solution: (for autotools)
In case there is src/$(project.libname).sym file, do this
1.) configure.ac: Add a check if platform linker supports version-script or not
2.) src/Makemodule.am: append --version-script or --export-symbols to LDFLAGS while
building a library
Do nothing if sym file does not exists. Tested with GNU linker on Linux, other platforms might need some conditionals ...
> Problem: can't create dso with versioned symbols

- README.md
- README.txt
- project.xml
- src/Makemodule.am
- zproject.gsl
- zproject_vs2015.gsl
I've added support for Microsoft Visual Studio 2015 build.
I basically grep'ed "vs2013" and added a corresponding vs2015 in each file where vs2013 is referred, as well as adding the zproject_vs2015.gsl targetting Visual C++ compiler v140 (VS2015).
I've tested the build process for the modified zproject under Ubuntu 14.04LTS and the new gsl file is correctly installed.
I hope I've not missed anything.
> Feature add vs2015 support

- zproject_automake.gsl
Problem: Generate blank line following trailing backlash in src/Makemodule.am
Solution: Correct blank line for section dist_api_DATA
> Problem: blank line following trailing backlash in src/Makemodule.am

- zproject_ci.gsl
- zproject_qt_android.gsl
Solution: use the new chmod_x gsl function to add execution rights to those files.
> Problem: execution right for various build scripts is not set after generation.

- zproject.gsl
- zproject_debian.gsl
Solution: generate most common files (rules, control and dsc) from
zproject_debian.gsl.
Note the generated output is usable in terms that one can get the
description and build a few .deb packages in a tool like Open Build
Service with a lot of warnings. It does not generate proper Debian
packaging info yet.
> Problem: need to write Debian recipes by hand

- zproject_class.gsl
Solution: generate main header with :c name mangling (foo-bar.h ->
foo_bar.h), this is follow up of cf5c2c0b
> Problem: project with hyphen in name have incorrect header

- zproject.gsl
- zproject_autoconf.gsl
- zproject_automake.gsl
Solution: detect the existence of .cc files in project and generate
proper autoconf and automake recipes.
I'd like to know your opinion if given approach sounds plausible to you.
> [RFC] Problem: no C++ support in generated autotools files

- zproject_bindings_ruby.gsl
Solution: Coerce polymorphic reference, in case it respond_to?(:__ptr).
This allows one to pass instances of the generated Ruby class. They'll
get coerced into an FFI::Pointer.
Other scenarios like passing in a FFI::Pointer, or nil (for C functions
where the NULL pointer is a valid argument) are be possible too now.
This also adds a bit of documentation about this versatile parameter
(slightly YARD specific).
> Problem: no conversion polymorphic reference

- api/myclass.xml
- project.xml
- zproject.gsl
- zproject_bindings_ruby.gsl
- zproject_class.gsl
- zproject_class_api.gsl
* add support for enums in the Ruby binding
* fix the processing of `<include ... />`
* GSL `c_method_declaration()`: don't treat all functions as polymorphic
* greatly extend the example API XML `api/myclass.xml`
Examples for the following API elements have been added:
* enums
* the implicit self pointer argument on destructors
* excluded methods (`exclude = "1"`)
* returned pointers which will be owned by the caller (`fresh = "1")
* arguments that are passed by reference (adds one more `*`)
* methods with `va_list` siblings (do_that() and vdo_that())
* arguments of type `byte`
* arguments of type `number`
* arguments of enum type (`enum:myclass.myenum`)
* arguments of type `string`
* arguments of type `buffer`
* arguments of type `size`
* arguments of type `FILE`
* arguments of type …
> enum types in Ruby binding and extended API XML example

- zproject_class.gsl
Solution: Read the comment from the xml file and add it to the enum definition
Fixes #306
> Problem: enum constant comments are not applied to the definition

- zproject_debian.gsl
- zproject_spec.gsl
Solution: Extend packaging templates a little bit using optional
parameters that let users to override automatic guesses.
> Problem: Can't specify real package names for dependencies

- zproject_spec.gsl
> Problem: spec doesn't require g++ for c++ projects

- api/myclass.xml
Solution: clarify its use in the example API.
This is related to the issue #310.
> Problem: use of attribute exclude = "1" unclear

- zproject_autoconf.gsl
Solution: Fix autoconf template not to lowercase function names we are
looking for.
> Problem: Can't check for functions that have uppercase letters in name

- zproject_spec.gsl
Solution: Support other READMEs than ones written in Markdown as well
and also make the whole README support optional.
> Problem: specs don't work without README.md

- zproject_class.gsl
Solution: use uppercase for macros, per convention
> Problem: inconsistent case in _library header

- zproject_automake.gsl
To get into more details, service file contains path to the
configuration but during the expansion of autotools macros we end up
with variable $prefix still present after expansion.
Solution: Not trying to be extra compliant with everybody and hardcoding
config to be in ${prefix}/etc/${package}/smt.cfg
> Problem: Service file generated using automake doesn't work

- zproject_bindings_ruby.gsl
Memory of fresh strings isn't free'd automatically when `FFI::Pointer` goes out of scope.
Solution: Wrap it in an `FFI::AutoPointer`.
Consider the following method API:
```xml
<method name = "encode">
Encode a stream of bytes into an armoured string.
<argument name = "data" type = "buffer" />
<argument name = "data size" type = "size" />
<return type = "string" fresh = "1" />
</method>
```
The corresponding C function might look like this:
```c
char * foo_encode(const byte * data, size_t data_size)
```
Note that the return value is a "fresh" string, which means the caller is responsible for destroying it when finished with it. Also note that it's not a struct of the class defined in this API or any other class. It must be a C style, NULL-terminated string.
It would be nice to have the …
> Problem: complicated fresh pointer handling in Ruby bindings

- zproject_bindings_ruby.gsl
Solution: Get rid of it and pass the relevant functionality as a Method
object (which is the preferred way according to FFI documentation
anyway).
As discussed in #322.
> Problem: superfluous class in Ruby binding

- zproject_autoconf.gsl
- zproject_automake.gsl
Solution: Add support for new <service> tag that will install whatever
is provided. Not generating it as project wide service is probably going
to be hand made.
> Problem: Need to install service not related to any main

- zproject_automake.gsl
This is different fix following up on c687d0a. c687d0a fixed service
files generated for local installation - aka just normal configure and
make install into /usr/local but it broke installation in packages where
system config directory is explicitly overridden to end up with
configuration in etc.
Solution: Return to the previous solution using sysconfdir but also
exporting prefix variable so it should work in both cases.
> Problem: Can't use configuration in packages

- zproject_class_api.gsl
Solution: remove this logic. Classes that need these methods should
simply define them. The extra cost is close to zero and it gives a
what-you-see-is-what-you-get API definition.
If we absolutely need to hide details that we see often in classes
there are other techniques. The best for classes (as it is well
known and not surprising) is inheritence. It is easy to do with
GSL. We've done this before in class models. The downside is you
start to get too many layers. The upside is you can ensure all
classes of a certain type are structured the same way.
At this stage I'd much prefer simplicity over abstraction. We are
already rather deep.
Fixes #332
> Problem: implied new/destroy/print are surprising

- zproject.gsl
- zproject_actor.gsl
- zproject_autoconf.gsl
- zproject_automake.gsl
- zproject_bench.gsl
- zproject_bindings_qml.gsl
- zproject_bindings_qt.gsl
- zproject_class.gsl
- zproject_cmake.gsl
- zproject_docs.gsl
- zproject_vs2008.gsl
- zproject_vs2010.gsl
- zproject_vs2012.gsl
- zproject_vs2013.gsl
- zproject_vs2015.gsl
The scripts used $(project.name:c).h in general. However for a first
class attribute of project, this seems fragile.
Solution: calculate project.header attribute at start and use in all
places it's needed.
Bonus: can be explicitly specified in project item if needed.
> Problem: ad-hoc calculation of project header name

- zproject_automake.gsl
Solution:
An example is 'xrap msg'. Therefore use 'substitute_non_alpha_to_make_c_identifier' instead.
> Problem: Classes may consist of multiple words separated by spaces

- zproject.gsl
Project <project name = "alerts-list" ...> ... </project>
generated 'include/alerts_list.h' instead of 'include/alerts-list.h' and
`make` did not compile.
SOLUTION: fix it by having zproject generate correct name of gsl
variable 'project.header'.
> PROBLEM: "include/$(project.header:)" generates a wrong file name

- zproject.gsl
Reverts zeromq/zproject#345
This is an invalid problem. CLASS does not allow a minus in file names instead everything MUST be separated by an underscore.
> Revert "PROBLEM: "include/$(project.header:)" generates a wrong file name"

- README.md
- README.txt
- zproject_bindings_python.gsl
- zproject_class_api.gsl
Solution: add project attribute to dependent classes
and use this instead of asking user to list all dependent
classes again.
This removes the need to manually list dependent classes
in every used project.
Fixes #353
> Problem: <use><class> is redundant

- zproject_bindings_ruby.gsl
According to discussion on
https://github.com/paddor/zproject/commit/908c355984010d3f42e518c2f6066eac33019477
This reverts commit 908c355984010d3f42e518c2f6066eac33019477.
> Revert "Problem: unnecessary Ruby exception classes"

- zproject_bindings_qt.gsl
Solution: Add comma if there are more than one argument besides the self_p.
> Problem: Argument comma separation is not correct for self pointers

- zproject_bindings_jni.gsl
Solution:
1. create topdir if does not exists
2. skip dependencies if project->dependencies are not defined
> Problem: zproject_bindings_jni fails to run

- zproject_spec.gsl
Solution: do not put cfg file to file list
> Problem: build of spec fails if main is marked as no_config=1

- zproject_spec.gsl
Solution: do not put main if private is defined to filelist
> Problem: spec with private main fails to build

- zproject_bindings_jni.gsl
Solution: return jbyteArray instead of long /ptr.
For this to work, the API must specify a 'size' attribute.
See czmq/api/zframe.xml for example of use.
> Problem: returned buffers are useless in Java

- zproject_bindings_jni.gsl
- zproject_class_api.gsl
This reverts commit 3d9bdde4208907066338e1ad88f37a12f5e46409.
This problem seems only half valid. See #368
> Revert "Problem: language bindings can't handle multiple constructors"

- zproject_autoconf.gsl
- zproject_automake.gsl
- zproject_spec.gsl
Solution: add support for main attribute tmpfiles = "1" (like service =
"1"), which generates template of proper tmpfiles.d config snippet.
Supported in autotools and spec generators
> Problem: installation of tmpfiles.d files is hacky in zproject

- zproject_autoconf.gsl
- zproject_automake.gsl
- zproject_spec.gsl
This reverts commit 504a6629fcfd4530e4d4bf4ac2b0f51d2dd493c5.
Per discussion on github I do agree with @hintjens that current
solutions exposes too many low-level details in the model. Lets drop it.
> Revert "Problem: installation of tmpfiles.d files is hacky in zproject"

- zproject_autoconf.gsl
- zproject_automake.gsl
- zproject_projects.gsl
- zproject_spec.gsl
Solution: add a support for new subelement <extra
type="systemd-tmpfiles" />. This way one can define additional data to
be installed without polluting main itself.
@hintjens feel free to express your opinions before merge. However I must say I like this approach :)
This extends already existing extra element by adding type parameter.
```
<main name = "foo" service="1"> Some daemon
<extra type="systemd-tmpfiles" />
</main>
```
The idea is that type will contain the name and installation location implicitly.
With this approach one can add type "systemd-service" and "systemd-service@" (or "systemd-service-template"??) and deprecate all attributes for main element.
> [RFC] Problem: main started to gain too many low level attributes

- zproject_class_api.gsl
generates:
```c
zthing * zthing_new()
```
instead of:
```c
zthing * zthing_new(void)
```
Solution: specify ```void``` if no arguments in API model
> Problem: C: empty parameter list: no void

- zproject_bindings_jni.gsl
Solution: define test method as static
This also removes the empty constructor on classes that use
arguments in their constructor.
> Problem: test method needs a class instance

- zproject_bindings_jni.gsl
This makes it impossible to kill a Java app using Ctrl-C.
Solution: disable CZMQ's SIGINT handling, when using JNI. A Java
app will still need to handle signals itself.
Note: this solution may not be valid; it still needs testing. The
usual technique in CZMQ apps is to trap SIGINT and then provide a
global (zsys_interrupted) that applications can check. Further, to
interrupt any blocking calls (recv) and return null.
I think we need to expose these two features to language bindings
via a new class in CZMQ.
> Problem: JNI binding traps SIGINT

- zproject_bindings_ruby.gsl
This applies to the `const char *` parameters, which are declared to the FFI library as `:string`, rather than `:pointer` (for convenience).
Unfortunately, the pretty strict coercion into a String will also coerce `nil` into the empty string. Removing the coercion alltogether solves the problem, as FFI would call #to_s on the argument to coerce it anyway.
Solution: don't force coercion into a String
> Problem: can't pass null pointer in Ruby binding

- zproject_bindings_ruby.gsl
Of course it's possible to hack around this in Ruby, but it's nicer to
have it available in a method like this.
Solution: extract undefining logic into a new method #__undef_finalizer
> Problem: need to undefine the finalizer in Ruby binding

- zproject_autoconf.gsl
- zproject_automake.gsl
Solution: "isolate" configure.ac/Makefile.am behind WITH_SYSTEMD
conditional, so service="1" and <extra type="systemd-tmpfiles"> are
built and installed only if configure --with-systemd is used.
@hintjens this implements your advice regarding system integration - it does not touch the model, just "isolates" unportable parts in build description.
> Project: system(d) files installation "leaks" to normal build

- api/myclass.xml
- zproject_class.gsl
- zproject_class_api.gsl
Solution: Declare an actor within a class. This allows the c generation
to generate the appropriate actor callback method but hides the callback
from the bindings.
> Problem: Cannot write an api for actors without exposing the actor method to the bindings.

- zproject_bindings_jni.gsl
Solution: when casting between jlong and pointer, use (intr_ptr)
intermediate cast to ensure that pointer is expanded to 64 bits
and truncated again properly.
> Problem: int/ptr warnings when building JNI on 32-bit system

- zproject_android.gsl
- zproject_ci.gsl
Solution: add `--depth 1` parameter to `git clone` commands
> Problem: build scripts don't need full git history

- mkapi.py
Solution: generate them from header files
*How to use*
`mkapi.py` needs [https://github.com/eliben/pycparser/|pycparser] installed. Use your package manager or pip to install it.
Test of functionality is done on headers from [https://github.com/zeromq/czmq/|czmq]. In order to make it work, you need [https://github.com/eliben/pycparser/tree/master/utils/fake_libc_include|fake_libc_include], which adds necessary declarations. However `fake_libc_include` is not a part of Python packages.
Usage is simple. Change dir to `tests/czmq` and run `python ../../mkapi.py -I/path/to/fake_libc_include include/czmq.h`. Result models will be in `api/` directory.
> Problem: I am lazy to write XML API models by hand

- zproject_debian.gsl
- zproject_spec.gsl
Solution: install systemd.pc and add --with-systemd configure flag to
both spec and debian recipes generators.
> Problem: systemd integration not enabled by default

- fake_cpp
Solution: add the hacky post processor fake_cpp - this removes some
glibc specific declarations pycparser can't deal with
> Problem: can't run mkapi

- fake_cpp
- mkapi.py
Solution: specify system preprocessor via --cpp argument. Two special
values:
* auto - try to autodetect the one (use clang on darwin/OS X, check gcc
and clang in PATH otherwise)
* none - don't call preprocessor at all - this expects input is already
pre-processed
This partially fixes https://github.com/vyskocilm/mkapi/issues/1
cc @paddor
> Problem: cpp is not default system preprocessor on OS X

- zproject_vs20xx.gsl
This caused Zyre to not build on Windows as czmq != libczmq.
Solution: use the use.project for dependency names.
> Problem: MSVC backend using wrong names for dependencies

- fake_cpp
- mkapi.py
Solution: drop more darwin specific attributes in fake_cpp, ignore weird
complex types in function arguments as they're not compatible with CLASS
anyway.
This should fix https://github.com/vyskocilm/mkapi/issues/1
cc @paddor
> Problem: can't run mkapi on OSX

- zproject_ci.gsl
I was half-way though making check-py and cmake work, but they're
not done, so there's no point asking for them in .travis.yml.
Solution: comment out the missing targets.
> Problem: .travis.yml asking for targets that don't exist

- zproject_debian.gsl
Solution: fix issues in rules, add missing compat file a and most important - generate proper install files, so we won't end with empty library and -dev packages.
> Problem: several issues found in generated Debian recipes

- zproject_android.gsl
- zproject_bindings_jni.gsl
Solution: build jar file containing the JNI classes, plus all
native libraries. Also pulls in dependent JNI classes. Native
libraries are put into lib/armeabi in the jar file.
Note: I've not yet tested that this works properly.
> Problem: does not build usable Android jar file for JNI

- zproject_android.gsl
- zproject_autoconf.gsl
Solution: use parallel make (-j 4) and don't build man pages.
Added --without-documentation switch to configure, as done in libzmq.
> Problem: Android build is too slow

- zproject_bindings_jni.gsl
Solution: copy from right place in NDK
> Problem: JNI Android jar is missing libgnustl_shared.so

- zproject_bindings_jni.gsl
Solution: specify all dependent libraries when building JNI library.
Specifically, in CMakeLists.txt, use target_link_libraries ().
> Problem: JNI layer failing to load .so's under Android

- zproject_cmake.gsl
Solution: use $(name:c) appropriately
> Problem: CMake has syntax error if class name contains space

- zproject_ci.gsl
Solution: add valgrind to Linux/OSX Travis CI build dependencies
zproject_automake.gsl explicitly calls Valgrind, so zproject_ci.gsl should add the build-dep to travis.yml
> Problem: memcheck needs Valgrind on Travis CI

- zproject_known_projects.xml
Solution: Make libsodium an optional dependency
> Problem: Cannot compile czmq without libsodium

- zproject_bindings_qt.gsl
Solution: Use one constructor as primary and implement the others as static methods.
> Problem: Qt Bindings cannot handle multiple constructors

- zproject_debian.gsl
Solution:
* add missing install suffix to main install file
* fix location for shared libs and pkgconfig files (there're in
usr/lib/<target>/
> Problem: generated install files are wrong

- zproject_class_api.gsl
Solution: use "msecs" type name instead
> Problem: "clock" type name is not explicit enough

- zproject_autoconf.gsl
- zproject_automake.gsl
Solution: add coverage target for make (autotools only), which will
generate nice html report using lcov && genhtml in coverage/ directory
> Problem: having code coverage report is hard task

- .gitignore
- .travis.yml
- ci_build.sh
What do you think of this solution for a CI? Rather than building a dummy project.xml, it uses CZMQ, which has many and various APIs. Should exercise most of the capabilities.
> Generate CZMQ project.xml as part of Travis CI build

- zproject_autotools.gsl
- zproject_class.gsl
- zproject_cmake.gsl
Revert previous commit, and add -DWITH_DRAFTS=1 to pkg-config in both cmake and autotools as discussed in #465 
Tested with czmq:
$ cat test.c 
#include "czmq.h"
main() {
printf("%d\n", zproc_czmq_version());
}
$ gcc `PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/home/lboccass/git/libczmq/src pkg-config --libs --cflags libczmq` -I/home/lboccass/git/libczmq/include -L/home/lboccass/git/libczmq/src test.c -o test
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lboccass/git/libczmq/src ./test
30003
> Fix for issue #465

- zproject_travis.gsl
Solution: do not run make check for dependencies, they are already
ran in their own CI and thus it is a waste of time to repeat those
tests again
I think it's not worth running dependencies tests, they are already run in their own repo. Especially with projects with many dependencies built from sources, like Malamute, it slows down a CI run by good chunk.
> Problem: Travis CI runs dependencies self tests

- zproject_autotools.gsl
People sometimes want to build libraries without any executables
at all.
Solution: re-enable the disable option on _selftest.
> Problem: selftest build must be optional

- zproject_qt.gsl
Solution: make qmake read the pkgconfig
By reading the pkgconfig qmake will set the draft API defines.
> Problem: qt bindings won't compile against draft APIs

- zproject_class.gsl
- zproject_class_api.gsl
...as you can re-generate headers pretty easily with "make code".
Revert "Problem: Re-generating zproto headers with zproject API model drops global verbose flag"
This reverts commit 24945ab93ecee3df2c1c878ed3f6e5865204072b.
> Problem: Previous patch adding variables was not really necessary.

- zproject_class.gsl
- zproject_class_api.gsl
Solution: refactor the resolution of constants into a function,
and call it from zproject_class.gsl before parsing a project's
global constants, so that "state" and "draft" are defined.
This problem causes a generation failure in Zyre. If this PR is accepted, I'll send a fix for Zyre with a regeneration and another fix. Also tested on CZMQ, doesn't change any generated file.
> Problem: global constant's state not defined

- zproject_cmake.gsl
Solution: when deciding if to enable draft APIs by default, instead of
checking for ".git" check for "${SOURCE_DIR}/.git".
> Problem: CMake out-of-tree builds won't see ".git"

- zproject_python.gsl
For example in malamute the protocol class contains constants with spaces which makes it invalid python code
> fix spaces in constant names generated by the python generator

- zproject_python_cffi.gsl
It was using functions with the same name, however we're using
a global scope, so this broke the python target.
Solution: use unique function names.
A better solution would be to wrap each target in its own scope.
I'll experiment with this.
> Problem: Python CFFI target broke the Python target

- zproject_autotools.gsl
E.g. if we modify an API model, we should be able to run 'make code'
and get new include files.
Solution: run 'gsl -target:- project.xml' in make code, after any
model generation.
> Problem: 'make code' does not rebuild the API

- zproject_travis.gsl
Solution: create builds/check_zproject before creating ci_build.sh
> Problem: check_zproject gen fails, missing dir

- Dockerfile
after zeromqorg/gsl accepts $GSL_BUILD_DIR environment variable
Solution: cleanup
> Problem: no need for WORKDIR

- zproject_python.gsl
Solution: generate a setup.py script.
To install bindings, run "python setup.py install".
> Problem: python bindings are not easy to install

- zproject_qt.gsl
Solution: Omit the "project->" prefix which then works fine.
The issue probably occurs because of the nested functions which are used
for namespacing.
> Problem: Qt dependencies are not resolve when selected with "project->"

- zproject_class_api.gsl
- zproject_java_lib.gsl
- zproject_qml.gsl
- zproject_qt.gsl
- zproject_ruby.gsl
Solution: exclude private classes when generating bindings
An example where this issue occurs is with czmq's zgossip_msg.
> Problem: zproject generates bindings for private classes

- zproject_autotools.gsl
Solution: use `$enableval` instead of `$withval`
> Problem: `--enable-drafts` is without effect

- zproject_ruby.gsl
Solution: Prepend class name and underscore
> Problem: wrong function names in warnings in Ruby binding

- zproject_android.gsl
Solution: if project.release is defined, clone from that branch
instead of master.
> Problem: Android CI ignores dep's release branch

- zproject_skeletons.gsl
Solution: allways call directory.create ('src')
This fixes
(zproject_skeletons.gsl 18) Can't open output file:
src/bios_agent_asset.c
> Problem: gsl project.xml fails if there's no src dir

- zproject_autotools.gsl
- zproject_class.gsl
- zproject_cmake.gsl
- zproject_known_projects.xml
Also fixes having a new line added to the headers every time the generation is ran. See individual commits for details.
> Make --with-systemd less ambiguous, fixes to CMake and autotools, add libsystemd in known projects

- zproject_autotools.gsl
- zproject_projects.gsl
Solution: get rid of it
This patch effectivelly drops
* services and no_config for main
* project.services
* main.extra
It preserve service attribute for main with the same semantics like back
then (one service file and one config file). Installation is still behind
WITH_SYSTEMD_UNITS variable, which seems like the most usefull idea of
all the changes we did.
> Problem: the installation model is uber messy

- zproject_autotools.gsl
Solution: change AC_ARG_WITH parameter to be "systemd-units" from
"systemd" to be coherent with help string and variables
> Problem: systemd-units option is broken #546

- zproject_travis.gsl
Solution: use --with-docs=no, as expected by the generated autoconf
> Problem: CI config option --without-doc is wrong

- zproject_autotools.gsl
Solution: define __STDC_FORMAT_MACROS for C++ projects
note: required by http://www.open-std.org/jtc1/sc22/wg14/www/docs/n851.htm
> Problem: C++ projects can't use inttypes.h macros

- zproject_skeletons.gsl
Solution: remove the first puts. In case main is started as verbose, the
same message appears twice, which is ridiculous enough. The zsys_info
below does the multitine support well.
> Problem: multiline comment in main generates invalid C skeleton code

- zproject_autotools.gsl
- zproject_class.gsl
- zproject_class_api.gsl
- zproject_cmake.gsl
It's clumsy that projects that don't even care about this aspect
are forced to use it, or they don't build properly. That is, the
project header is useless on projects consisting only of draft
classes, which is the default for new projects.
Solution: always build drafts on projects that have no stable
public classes.
Fixes #550
> Problem: drafts are confusing on many projects

- zproject_class.gsl
- zproject_travis.gsl
Stable build is currently broken on CZMQ due to this (ZGOSSIP defines missing).
Also add a stable build test to the CI, to make it easier to spot breakages.
> Problem: draft constants, typedefs and enums not added to internal header

- zproject_debian.gsl
Solution: see individual commit.
Main change is to not generate the .dsc file, as it's generated by the debian packaging tools at build time., so it's wrong to generate it here and check it in the source tree. But more importantly, its presence in the source tree breaks CZMQ build in a real-world scenario, when using the OpenBuildService: http://openbuildservice.org/
At build time, dpkg-scansources is ran after the git-buildpackage service creates the source tarballs and the .dsc file. dpkg-scansources does a recursive search from the working directory, and so it finds the .dsc generated by zproject in the source tree, and fails because it's malformed, incomplete and unexpected.
> Problem: Debian recipe has various issues

- README.md
- README.txt
- api/myclass.api
- zproject_class.gsl
- zproject_class_api.gsl
- zproject_java_lib.gsl
- zproject_nodejs.gsl
- zproject_python.gsl
- zproject_python_cffi.gsl
- zproject_ruby.gsl
These are just constants, yet the syntax for defining and using
them is complex and does not solve any identifiable problem except
"maintain compatibility with existing header files".
As well as being complex to specify and use, they're a pain to
implement in bindings.
The simplest solution is to use constants. I've done that in CZMQ
and Zyre and now here in zproject.
Solution: use constants.
Fixes #460
> Problem: enums are over-engineered

- zproject_autotools.gsl
problem: old error message was just an undefined item error
solution: check that test exists first, give error that leads user towards solution
> add error message for missing test field

- zproject_redhat.gsl
Solution: use --with-systemd-units (changed in ed6d506d)
> Problem: configure line in generated spec is wrong

- zproject_debian.gsl
Solution: add it to Build-Depends
> Problem: dh-systemd not referenced in Build-Depends

- README.md
- zproject_class.gsl
- zproject_skeletons.gsl
Problem: don't want self tests generated for some thing (bringing in a class that is generated by protobuf-c is a good example)
Solution: add notest to class/actor which will optionally not generate self test and will not include file in self_test
> add notests to zproject

- zproject_ruby.gsl
Solution: generate them from the API models
> Problem: constants aren't generated in Ruby binding

- tstgenbld.sh
Solution: removed '-target:*' from GSL command line, letting it be driven
by project.xml settings instead.
> Problem: tstgenbld.sh incorrectly regenerating all targets

- zproject_nodejs.gsl
Solution: add 'nothing' to list of known return types
> Problem: [nodejs] void methods not being exported

- zproject_travis.gsl
Solution: Remove memcheck from the travis build.
During the last months `make memcheck` caused all zproject based builds to
fail because there are supposedly memory leaks within other layers of the
software e.g. libzmq, which causes the build to fail all the time. IMO
the memcheck should be run manually in addition to testing and not by
travis itself.
> Problem: [travis] make memcheck causes failing builds all the time

- zproject_autotools.gsl
Solution: chdir to project home before gsl script processing
> Problem: make code target not work in out of source builds

- zproject_class.gsl
Solution: see commits:
> Problem: methods use typedef defined after them
> Solution: in src/<project>_classes.h define typedef and constants
> first and method later, like in the public headers, otherwise
> compilation will fail with draft API disabled.
> 
> Problem: draft API defined twice, breaks build
> Solution: wrap definition of DRAFT APIs in the src/project_classes.h
> private header in ifndef DRAFT. This will avoid build problems caused
> by having some items defined twice, in the public and in the private
> headers, when building with DRAFT enabled. At the moment it only
> affects typedefs, but it's cleaner and more future-proof to wrap the
> whole definition rather than one item here and there.
> Problem: project build broken with draft typedefs

- zproject_vs20xx.gsl
Solution: corrected support to --disable-drafts and --enable-drafts cmd line options
Note: presence of .git directory at main level still implies enable DRAFT APIs same as before if no cmd line options are present. If present, the requested cmd line optiont takes precedence.
> Problem: configure.bat incorrectly supports --disable-drafts option

- zproject_autotools.gsl
Solution: Use the prefix attribute instead which must be correct for all dependencies.
> Problem: [autotools] libname fails to do library check on some deps

- zproject_java.gsl
Solution: Adjust README to take TOOLCHAIN_VERSION environmental variable into regard.
> Problem: [jni] Build instruction for android incomplete

- zproject_java_msvc.gsl
- zproject_nuget.gsl
- zproject_vs20xx.gsl
Solution: Added check for environment variable ECHOON. If set to "on" all
scripts behave as if @echo on is first line.
Reset also after every call to scripts that would turn echo off, such as
DevStudio provided scripts.
> Problem: No easy way to debug windows batch scripts

- zproject_autotools.gsl
Solution: Use `builddir` instead of `srcdir` to point to the selftest
executable. This is necessary because distcheck does build out
of source.
> Problem: [autotools] check-local causes `make distcheck` to fail.

- zproject_autotools.gsl
Solution: Tell automake to build zip as well as tarball.
> Problem: [autotools] make dist does not build zip by default

- configure.ac
- src/Makemodule.am
- zproject_travis.gsl
Solution: Use travis to deploy these artifacts to github automatically.
The deployment is triggered by tagging on master branch of the
repository. Travis will trigger deployment on the default build
and will in process disable drafts.
For now the results of `make distcheck` are deployed
as well as their md5 and sha1 hash sums.
> Problem: [travis] deploying release artifacts is a manual process

- zproject_redhat.gsl
Solution: check the existence before adding to filelist
> Problem: generated spec is bad if there is no COPYING file

- zproject_travis.gsl
Solution: Build and deploy android jar file when tagging a release on github.
> Problem: [travis] travis does not deploy android jar when tagging

- zproject_java.gsl
Solution: Change executable flag after generating file
> Problem: [jni] jni bindings ci_build script not executable

- zproject_autotools.gsl
Solution: Add the cmake stuff to EXTRA_DIST
> Problem: [autotools] cmake stuff not included in release tarball

- zproject_autotools.gsl
Solution: replace them with the generic project name
> Problem: [autotools] configure does contain czmq references

- zproject_class_api.gsl
Solution: It is common practice to have dependent CLASS project in the
same workspace directory. Thus zproject should search for api files
from dependencies within the workspace.
> Problem: [api] dependencies in workspace are not resolved

- zproject_autotools.gsl
... if it contains hyphen
Solution: do not use :c formatting for man1 pages and use original name
instead. Also change mkman to accept exactly two parameters.  This will
give us main foo-bar and man page foo-bar.1 (instead of foo_bar.1).
> Problem: man page is not consistent with main name

- zproject_autotools.gsl
- zproject_debian.gsl
- zproject_redhat.gsl
Solution: add this support + small fix of my previous PR + fix of type in redhat recipe
Tested for both Debian and Redhat (CentOS) builds
>  Problem: generated packaging recipes does not include documentation

- zproject_travis.gsl
Solution: Checkout all dependencies before checking if zproject is current on travis.
> Problem: Missing project dependencies will cause wrongful output

- zproject_travis.gsl
Solution: Clone the to the common working directory
> Problem: [travis] check_zproject clones dependencies to wrong directory

- zproject_travis.gsl
Solution: reset wd to correct location for every dependency
> Problem: travis check_zproject script gets lost in working dirs.

- zproject_java.gsl
- zproject_travis.gsl
Solution: Instead of hardcoding the path export the builddir
> Problem: [jni, travis] pkgconf path is wrong for deployment

- zproject_java.gsl
- zproject_travis.gsl
Solution: row back to hard-coded path for pkgconf directory, but this
time without typo :)
> Problem: [travis, jni] build script exports are not available in deploy

- zproject_autotools.gsl
Solution: fix variable name from oupt to outp.
> Problem: [autotools] var name typo in mkman

- zproject_autotools.gsl
Solution: add a markdown fence to enable code highlighting in markdown.
zeromq/gitdown#18
> Problem: markdown docs have no code highlighting for interfaces/tests

- zproject_cmake.gsl
Problem: [cmake] test timeout is weirdly low
Problem: [cmake] no make target to cleanup cmake generated files
Problem: [cmake] distclean does not remove executables
> cmake test timeout + better cleanup

- zproject_cmake.gsl
Solution: Tell cmake to use the loaded pkg-config CFLAGS. This is needed to
compile against draft apis.
> Problem: [cmake] pkg-config CFLAGS not used when compiling

- zproject_cmake.gsl
Solution: create it beforehand.
> Problem: [cmake] generation fails if builds dir doesn't exist

- zproject_cmake.gsl
Solution: generate a JSON Compilation Database.
This compilation database can be used by IDE tools to check for syntax
error.
> Problem: [cmake] no information about individual compile step

- zproject_class_api.gsl
Solution: Handle undefined directory object, instead of directly dereferencing it
* This is a way to reduce the severity of #655 for me
> Problem: Error when class API not found, rather than warning.

- src/Makemodule.am
needed to re-run and commit src/Makemodule.am
travis seems to have not complained on this build (my account):
https://travis-ci.org/wesyoung/zproject/builds/144563619
but might wanna check to see that it builds under this project just to be sure before merging.
> problem: makemodule missing zproject_vagrant.gsl

- zproject_class_api.gsl
Solution: improve search criteria to require that method with matching name also have a 'va_list' argument
Replaced code erroneously determined zdir_patch.vpath to be a va_list sibling of zdir_patch.path
> Problem: search for 'va_list siblings" finds methods that don't meet requirements

- zproject_debian.gsl
- zproject_known_projects.xml
This is still work in progress, the _service is not nailed down yet, working on it with @sappo but I don't think the .dsc will need changes anymore hopefully.
Note that to avoid breaking dpkg-scansources and native debian builds the dsc file has a .obs suffix, and then the _service renames it.
> Problem: cannot build debian package on OBS

- zproject_redhat.gsl
Solution: Use ghostscript dependency instead.
The ghostscript dependency is required by graphviz which is required
by asciidoc. Usually this dependency is automatically resolved but
Fedora 24 has problems finding the correct one. Thus we add the
dependency here as workaround!
> Problem: [redhat] ghostscript-core dependency not available on openSUSE

- zproject_rpi.gsl
Solution: Add a script which pulls the latests raspbian image, extends
it so extra software can be installed into it. Then cross compile
and install to image.
The user can copy the image to an SD card without further action(s).
> Problem: [rpi] installing project to an raspbian image is tricky

- zproject_autotools.gsl
- zproject_debian.gsl
- zproject_redhat.gsl
Solution: refactor the doc discovery into a separate function, and
call it in the debian and redhat packaging in order to include the
manpages only if they are generated, to avoid a build failure due to
non existing files
> Problem: man1/3/7 unconditionally installed in debian/redhat

- zproject_valgrind.gsl
Solution: suppress it via valgrind suppression file,
because the memory is allocated by libc itself, it lives in
static area, so will be automatically free'ed on program
end.
See
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66339
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64535
http://stackoverflow.com/questions/32933301/valgrind-and-stdunique-ptr-false-positive-or-not
https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=219988
KDE did the same, to suppress this message
https://bugs.kde.org/show_bug.cgi?id=345307
> Problem: g++ 5.10 generates "memory leak"

- packaging/debian/rules
- packaging/redhat/zproject.spec
- zproject_debian.gsl
- zproject_redhat.gsl
Both a manual build and an OBS build solution is added.
@sappo - with this, we can create a git-draft project and just linkpac to the main project, and add the option to the prjconf. When the main project packages are triggered the draft one will be triggered too, so we get around the single-target limitation of the Github hooks.
> Problem: cannot build packages with DRAFT APIs

- zproject_class.gsl
Solution: roll back duplicate declarations for functions that have
a format index parameter.
This will make the docs a bit uglier, by appending the CHECK_PRINTF
macro at the end of the signature in the doc.
But a duplicate declaration in a public header breaks the build of
any project that uses the library and includes them, and also builds
with -Wredundant-decls.
/usr/local/include/zcert.h:128:5: error: redundant redeclaration
of ‘zcert_set_meta’ [-Werror=redundant-decls]
zcert_set_meta (zcert_t *self, const char *name, const char
*format, ...) CHECK_PRINTF (3);
^
/usr/local/include/zcert.h:64:5: note: previous declaration of
‘zcert_set_meta’ was here
zcert_set_meta (zcert_t *self, const char *name, const char
*format, ...);
Fixes #634
I'm open to a different solution that doesn't add …
> Problem: build failures due to Wredundant-decls

- AUTHORS
- zproject_cmake.gsl
- zproject_cygwin.gsl
- zproject_mingw32.gsl
- zproject_vs2008.gsl
Solution: Replace $(PROJECT.LIBNAME)_EXPORTS and
LIB$(PROJECT.LINKNAME)_EXPORTS with $(PROJECT.PREFIX)_EXPORTS.
$(PROJECT.LIBNAME)_EXPORTS was renamed to $(PROJECT.LIBNAME)_EXPORTS at
e1f838d5633c7ccd26f8fa49d8678852f7b039be but some build types such as
CMake don't follow the change.
> Problem: $(PROJECT.LIBNAME)_EXPORTS is still used

- zproject_cmake.gsl
Solution: Respect the specified CMAKE_BUILD_TYPE value. If users don't
specify CMAKE_BUILD_TYPE, auto CMAKE_BUILD_TYPE set is used. Normally,
users don't specify CMAKE_BUILD_TYPE, so the behavior isn't changed.
> Problem: Can't build Release type with "git clone"d source

- zproject_ruby.gsl
As the fallback type, it has been treated as a pointer. But it's an int
on Unix and an uint64_t on Win64 (AFAIK).
Solution: Support it on Unix and Win64.
This also improves the code readability a bit.
> Problem: Ruby binding doesn't handle "socket" return type

- zproject_ruby.gsl
On some Mac environments I use, homebrew is installed in /opt/brew directory.
So I want to supply a path where libczmq.dylib is installed by an environment variable.
This pull-request introduces LIBCZMQ_PATH environment variable for this purpose.
> Look up LIBCZMQ_PATH in ruby binding

- zproject_autotools.gsl
- zproject_cmake.gsl
Solution: add dependencies, if necessary, to the .private Libs field
of the pkgconfig file at build time.
This way pkg-config --static --libs libfoo will correctly print
dependencies if they were used to build the static libfoo.a library.
> Problem: pkgconfig file does not support static link

- zproject_rpi.gsl
Solution: Extend the script to allow incremental builds. This will
only re-build the current project. Also add an option to update the
dependencies and don't update them by default.
> Problem: [rpi] build script always re-compiles dependencies

- zproject_docker.gsl
- zproject_vagrant.gsl
Solution: Use tarball if present to build CI, Docker or Vagrant.
> Problem: tarball dependencies still require repository

- zproject_python.gsl
this was the only semi-clean way i was able to solve #705, especially in cases where you may have multiple shared objects embedded within a python library (think: libzyre.so depends on libczmq.so which also depends on libzmq.so and assume they are all under site-packages/czmq and site-packages/zyre instead of LD_LIBRARY_PATH).
i tried testing it both ways in some fresh vm's (loading the original way, and the new way), both seem to check out. once (/if?) this is merged, will submit PR's for new bindings in zyre and czmq.
i'm open to other ways of solving this problem, but most of them deal with modifying LD_LIBRARY_PATH and actually reloading the interpreter, which seems like a bit more complicated code than just dropping in and out the path to see if things load properly..
> problem: python bindings do not check for bundled shared objects first

- zproject_ruby.gsl
Just like functions marked as DRAFT, functions marked as DEPRECATED can
be unsupported by the currently installed library too.
Solution: Handle their unavailability gracefully as well. When an
unavailable function is called anyway, raise NotImplementedError with a
helpful message.
> Problem: deprecated functions can be unavailable

- zproject_class.gsl
Solution: if a class is private, don't add its $class_test to the
list in $project_selftest, as the symbol should not be visible
externally.
Instead, the public class that uses the private one should call the
private one's test during its own.
> Problem: selftest binary tries to use private class symbol

- zproject_class.gsl
Solution: define a project_PRIVATE macro that uses gcc/icc
visibility "hidden" attribute to instruct the compiler not to export
symbols privately defined in $project_classes.h when --enable-drafts
is disabled.
> Problem: DRAFT symbols are leaked as public

- zproject_java.gsl
Solution: Override version artifact by default so it wont cause
deployment failures.
> Problem: [jni] bintray deploy fails if version exists

- zproject_java.gsl
Solution: Upgrade bintray plugin to 1.7.2 which solves the problem.
> Problem: [jni] bintray override option doesn't work with current version

- zproject_autotools.gsl
Solution: add "doc" target to regenerate the docs instead
> Problem: autotools clean target calls mkman

- .gitignore
- README.md
- builds/cmake/ci_build.sh
- ci_build.sh
- tstgenbld.sh
- zproject_cmake.gsl
- zproject_docker.gsl
- zproject_git.gsl
- zproject_rpi.gsl
- zproject_travis.gsl
- zproject_vagrant.gsl
Solution: improve several points so a freshly generated project passes the GitHub/TravisCI tests; rename downloaded Git-sourced projects into `*.git` directories and add those to `.gitignore`
Note: not done for some platform scripts I'm less sure about (android, java, ...) - these might rely on particular directory names and a new suffix might break them. Someone expert in those areas may follow up later.
> Problem: generated Travis tests do not work out of the box as well as they could, and .gitignore needs updates

- configure.ac
- zproject_autotools.gsl
Solution: these newish (not XX-century standard) functions are available, but require -D__EXTENSIONS__ to be set... do it by default.
> Problem: on Solaris/illumos projects fail compiling strdup() et al

- zproject_travis.gsl
...and warnings are often not just noise - this code can explode under certain conditions (different bitness, OS, etc.)
Solution: Add a Travis target which enables all warnings and makes them fatal. Currently only for GCC and should not impact other compilers if available on Travis, but structure allows easy extension to e.g. CLANG compilers if someone knows them well.
> Problem: Travis does not ensure warning-less code

- .gitignore
- zproject_git.gsl
Solution: default gitignore should hide the distcheck workspace directory, tarball and zipfile
> Problem: distcheck products are seen in git status

- zproject_travis.gsl
Solution: enable it in the default build target.
This will also allow to ship docs in the Travis-driver releases on
Github.
> Problem: Travis CI does not check docs build

- .gitignore
- zproject_autotools.gsl
- zproject_git.gsl
- zproject_travis.gsl
Solutions: Update the default .gitignore template with more exclusions; yell if the file already exists and so will not be overwritten
Follow-up to https://github.com/zeromq/czmq/pull/1568
Minor other fixes
> Problem: Template for gitignore was not updated for a regenerated CZMQ project

- zproject_autotools.gsl
Solution: make it a bit more robust and future-proof by looking for C/C++ sources not in `$srcdir_of_doc/../src` but in `$top_srcdir_of_project/src`.
Currently these are equivalent (with docs being in `$top_{src|build}dir_of_project/doc`), but the latter form is less expected to change.
> Problem: docs generation assumes certain relative directory layout in the project

- zproject_autotools.gsl
Solution: adjust new lines vs backslash generation logic to account
for the case where there is only one class with an engine
> Problem: if only one class with engine, automake is broken

- zproject_debian.gsl
Solution: remove it. It doesn't make sense to Build-Depend on systemd
as it's not necessary to enable support for it in a service,
dh-systemd is enough.
> Problem: Debian pkg has build-dep on systemd

- zproject_debian.gsl
Solution: remove it from the generated .dsc file too
> Problem: Debian pkg still build-deps on systemd

- zproject_debian.gsl
Solution: add them to the -dev package
> Problem: debian pkg does not ship API files

- zproject_known_projects.xml
Liblognorm now uses libfastjson instead of json-c.  This PR adds libfastjson as a known project, and changes the lognorm dependency to use it rather than json-c.
> Problem: lognorm deps out of date

- project.xml
- zproject_travis.gsl
Solution: make the new distcheck project config option opt-out
instead of opt-in.
Correct handling and creation of distributable tarball is core to the
github and travis based releases scripts that zproject generates, so
by default it should check that everything works correctly.
Retain the option so that users, if they intend to do so at their
risk, can disable this check in their projects.
> Problem: make distcheck is no longer ran by default

- builds/cmake/ci_build.sh
- configure.ac
- zproject_autotools.gsl
- zproject_cmake.gsl
- zproject_java.gsl
- zproject_rpi.gsl
- zproject_travis.gsl
Solution: use autoreconf (or the explicit chain of calls) in this case
> Problem: Should support dependencies that lack autogen and precompiled configure script

- Makefile.am
- configure.ac
- zproject_autotools.gsl
Solution: have ./configure script detect the presence of $srcdir/CMakeLists.txt and based on that - makefile should list them among EXTRA_DIST (or not), effectively making CMake support optional (now hardcoded among default targets for project.xml)
> Problem: projects which choose to not track CMake recipes fail distcheck

- zproject_travis.gsl
Solution: implement builddir support for Valgrind too
> Problem: the Valgrind part of Travis CI does not honor builddir

- zproject_travis.gsl
Solution: Use PWD to navigate back to the original directory
> Problem: Using builddir has implication when going back

- configure.ac
- zproject_autotools.gsl
- zproject_travis.gsl
Solution: as a take on issue #734, take the least intrusive and fragile choice: enable ccache and stashing of the ccache contents from recent build of the project done in same conditions (independently for each zproject-generated project). As a result, code checkouts, autogen's and configure's are still done (of which checkouts and autogens can be parallelized with no loss in consistency, as a later improvement, when/if we ensure which projects have autogens that only require common OS programs and do not want something from installations of built other dependencies), but compilations run quickly since most object files are still applicable. Where zeromq-ecosystem prerequisites used to take 2 minutes, now it is between 30 and 60 seconds, as tested in a few runs on a pet project.
Also …
> Problem: Travis tests are slower than they can be

- .gitignore
- README.md
- builds/cmake/ci_build.sh
- ci_build.sh
- tstgenbld.sh
- zproject_autotools.gsl
- zproject_cmake.gsl
- zproject_docker.gsl
- zproject_git.gsl
- zproject_rpi.gsl
- zproject_travis.gsl
- zproject_vagrant.gsl
@sappo @jimklimov as far as I can see the change to clone into *.git from https://github.com/zeromq/zproject/pull/722 was for the .gitignore purposes. This alternative solution achieves the same end result, but without all the problems caused by the directory name being different from the project names.
I was going to implement all the necessary workarounds instead, but it ended up being quite ugly and special-cased, which I don't think is the right approach for a generic code generation tool.
I hope this is ok for you Jim, let me know if it causes you any issues and we can revert/revisit.
> Problems: .git suffix in CI cloned directories causes issues and various cleanups

- zproject_ruby.gsl
Solution: Use :uint64 instead. It's available.
> Problem: :uint64_t is used but ffi gem doesn't provide it

- zproject_travis.gsl
…rather than to `$BASE_PWD` (this can have adverse effect if the project has a defined subdir with sources for build - e.g. not the tarball root)
Solution: Carry over BASE_PWD from git-build clause
> Problem: When building tarballs, zproject_travis.gsl returns to ".."

- zproject_java.gsl
Solution: Upgrade to most recent version which fixed java 1.7 compatibility
> Problem: [jni] bintray deployment fails due to java 1.7 incompatibility

- .travis.yml
- builds/check_zproject/ci_build.sh
- builds/cmake/ci_build.sh
- ci_build.sh
- tstgenbld.sh
- zproject_android.gsl
- zproject_cmake.gsl
- zproject_java.gsl
- zproject_rpi.gsl
- zproject_travis.gsl
…Also, CI scripts are unavoidably traced (hardcoded "set -x").
Solutions: to find bottlenecks and prove improvements in Travis integration, the steps (build and test of prerequisites and project itself) should be profiled, at least by adding date'd echo's and time'd invokations. Add CI_TRACE toggle as a Travis global envvar to toggle "set -x" in CI scripts. Per discussion of earlier PoC, make this activity togglable (and invisible by default).
Currently timing is enabled in travis.yml for zproject itself, but disabled by default in generated travis files. Tracing is disabled by default in both cases.
> Problem: build steps in Travis tests take unknown time, profiling needed

- zproject_cmake.gsl
Solution: check scope before adding an install rule
> Problem: cmake installs private executables

- .travis.yml
- builds/cmake/ci_build.sh
- zproject_cmake.gsl
- zproject_java.gsl
- zproject_travis.gsl
Solution: when travis tests go south, more insight can be desired - so make the quiet configure operation default, but togglable
> Problem: unavoidable "configure --quiet" obstructs justice

- zproject_autotools.gsl
- zproject_bench.gsl
- zproject_class.gsl
- zproject_git.gsl
- zproject_nodejs.gsl
- zproject_qml.gsl
- zproject_qt.gsl
- zproject_ruby.gsl
- zproject_skeletons.gsl
- zproject_travis.gsl
- zproject_valgrind.gsl
Solution: wherever "!file.exists()" check is used, report that a file was not overwritten (and propose an estimate if it matters or not - e.g. should the user move away the existing file and re-run GSL, or not)
> Problem: when regenerating a zproject, we don't know which existing files were skipped

- zproject_autotools.gsl
Solution: For "language!=cxx" projects, mkman should fall back from missing .c sources to trying .cc
> Problem: If a project has both .C and .CC sources, it can not build docs

- zproject_autotools.gsl
Solution: also fallback from C to CC if header == source (MAN1 codepath)
> Problem: recent fix to mkman did not fallback for headers

- zproject_autotools.gsl
Solution: when regenerating a project, warn the user about present obsolete version.sh (followup to https://github.com/zeromq/zproject/commit/2993efe965c2f5bc740e28c226b74e57177e59b5 which dropped it)
> Problem: stale version.sh files can break builds

- zproject_debian.gsl
Solution: Re-insert comment as GSL comment so the OBS build service
will not break.
> Problem: [debian] removed comment used a reminder

- zproject_travis.gsl
Solution: copy over support for non-default releases (git branches); comment what the blocks do logically
> Problem: check_zproject script did not consider git branches (releases)

- README.md
- project.xml
- zproject_autotools.gsl
- zproject_known_projects.xml
- zproject_projects.gsl
Solution: add support for optional maximum and next known-incompatible versions
Verified to produce reasonable output in both `configure.ac` and `*-pc.in` files.
> Problem: zproject allows to constrain only minimal version of dependency

- packaging/debian/control
- packaging/debian/zproject.dsc.obs
- zproject_debian.gsl
Solution: shuffle around the required package names so the end of list is definitive
> Problem: generated debian control file ended a list with comma

- zproject_class.gsl
Investigation step 1 - visibility : in projname_selftest.c(c) report what features a selftested class has (draft/stable, private/public)
> Problem: Self-test skeleton is inconsistent

- packaging/debian/control
- packaging/debian/zproject.dsc.obs
- zproject_debian.gsl
Try to fix fallout from PR #803
> Debian: no empty lines must be between Build* tags

- zproject_debian.gsl
- zproject_redhat.gsl
Solution: rather than fixed `$name.service` strings, allow packaging of certain globs on top of this.
TODO: Test resulting markup with some packaging system (OBS?); by docs globs should be supported.
> Problem: different systemd units can be delivered by projects

- zproject_autotools.gsl
- zproject_class.gsl
- zproject_cmake.gsl
- zproject_cygwin.gsl
- zproject_gyp.gsl
- zproject_mingw32.gsl
- zproject_vs2008.gsl
Solution: add a new module, $project_private_selftest, which will
call every private class selftest function. This module exposes a
single void $project_private_selftest (bool verbose) function which
is then called from the selftest binary.
This way there is a single, common and stable public symbol and
private classes symbols are not exposed.
Note that for now it's exposed as a DRAFT functionality to allow for
testing.
Fixes #808
> Problem: need to automate self-testing of private classes

- zproject_known_projects.xml
Solution: use libuuid-dev to use util-linux library instead of the
very old and unmaintained ossp uuid
> Problem: uuid redhat package name uses old library

- zproject_class.gsl
- zproject_skeletons.gsl
Solution: declare functions with $project_PRIVATE macro to avoid
leaking the symbols when building with DRAFT APIs
> Problem: draft private classes symbols leaked when built with draft

- README.md
- project.xml
- zproject_autotools.gsl
- zproject_class.gsl
- zproject_cmake.gsl
- zproject_debian.gsl
- zproject_projects.gsl
- zproject_redhat.gsl
- zproject_travis.gsl
Solution:
* enable fallback testing if pkg-config data not present
* enable opting-out of redhat and debian package install/req/check by providing empty string as the name
Usecase that passes build is:
````
<use project = "lua-5.1-redhat" libname = "lua" prefix="lua"
optional = "1" am_lib_macro = "LUA_5_1"
min_major = "5" min_minor = "1" mit_patch = "0"
debian_name="" redhat_name="lua-devel"
test = "lua_close"
/>
<use project = "lua-5.1-debian" libname = "lua5.1" prefix="lua"
optional = "1" am_lib_macro = "LUA_5_1"
min_major = "5" min_minor = "1" mit_patch = "0"
debian_name="liblua5.1-0-dev" redhat_name=""
test = "lua_close"
/>
````
> Problem: got issues building against lua

- zproject_travis.gsl
Solution: call string.replace in travis script, like debian do
cc @jimklimov
> Problem: underscore is not valid debian package name

- README.txt
- zproject.gsl
- zproject_autotools.gsl
- zproject_debian.gsl
- zproject_install.gsl
- zproject_redhat.gsl
Solution: introduce zinstall, the zero model for file installation
The beauty of this model (as opposite of PR#539) is that it impose clear
protocol between model and rest of the generators. This protocol are
files in builds/zinstall/, which are then included in generated files.
This has two main advantages over older attempts
1. installation model fully implemented in ONE place
2. because of the protocol, there can be more models w/o any impact on
backend
Design goals are stated in README.txt, but let's repease
1. KISS - the less options the better
2. No conditionals - please don't create an another half-baked XML
programming langugage like ant
3. Real problems - don't add more options because you can
... or you will get replaced by zinstall2 ;-)
foundation for closing #810
cc @bluca …
> Problem: can't install additional files via project.xml

- zproject_autotools.gsl
Solution: beside checking under srcdir/.git, also ask GIT if it can find the workpace up the tree
Follow-up to discussion in #820 : now `make all && make distcheck` is consistent regarding enablement of Draft API by default (without explicit flags) when running somewhere under a git repo.
> Problem: make distcheck does not see it is under .git repo

- Makefile.am
- zproject_autotools.gsl
Solution: Define the cleanup variables in main generated makefile, so the manual one can always just append (and not risk overwriting something a later version of zproject might put there)
> Problem: It is risky to always define CLEANFILES etc. from scratch in Makemodules-local.am

- zproject_debian.gsl
- zproject_redhat.gsl
> Problem: cfg.example magically added to debian/rh recipes

- zproject_install.gsl
Solution: install it only if main is enabled
> Problem: zinstall: tmpfiles installed even if main is disabled

- zproject_cmake.gsl
for windows build, the .exe should not be separated from executables. this makes interactive debugging in visual studio easy, and allows to fix the execution of unit test on appveyor, see https://github.com/zeromq/czmq/pull/1601/
I do not know if this change should be msvc only or could be applied for all platforms
(BTW is cmake used only on windows ?)
> do not use specific locations for executables

- README.txt
- zproject_install.gsl
Solution: add type="config" to zproject_install.gsl
> Problem: want to install additional config files

- configure.ac
- zproject_autotools.gsl
- zproject_known_projects.xml
- zproject_projects.gsl
Solution: start from revised code of PR #838 and add support for alternate `pkgconfig` names (which is what we actually use in the configure script queries, rather than abstract `libname`) so that different spellings of the metadata can be checked with one `<use>` statement.
Based on this, add support for easily including LUA 5.1/5.2 as a single known project (and hopefully working on all relevant platforms despite their naming differences):
````
<use project = "lua-5.1" />
````
Note: This PR currently only completes the search for several pkgconfig metadata names. Supporting code is similar (and was added) for compilation tests so they could try different `-l${linkname}` values as well, but that loop was not finished and committed yet.
Attn: @vyskocilm @karolhrdina
> Problem: only one pkg-config metadata name is inspected

- zproject_class.gsl
Solutions: Reverse order of including files - extra first, class definitions - next.
> Problem: types defined by extra include files can't be used in class definitions

- zproject_class.gsl
- zproject_skeletons.gsl
Solution: move forward class type defintions from class include file to _classes.h file.
> Problem: class type definitions can't be used by other classes

- zproject_class.gsl
platforms the macro is disabled by default (windows/release for example)
solution: warn the user, when the assert macro is disabled, that the tests
will be meaningless
> problem : self tests must be run with assert macro enabled, but on some

- zproject_cmake.gsl
Solution: do not use specific locations for executables.
Cherry-picked from https://github.com/zeromq/czmq/pull/1601
> Problem: CMake Windows test runs are broken

- zproject_class.gsl
Solution: use ifdef guards around forward declarations in the common
header for private classes typedefs like zproto does, to avoid build
errors
> Problem: double definitions when using zproto

- README.md
- project.xml
- zproject_autotools.gsl
- zproject_debian.gsl
- zproject_redhat.gsl
Following up on #811 - it seems that debian always and RPM sometimes do not well support globs. So another solution is proposed to better handle the single-instance and/or multi-instance service units. Non-service units are left for the future, so far no released zproject version shipped them out of the box.
> Do not use globs for systemd unit files

- README.md
- zproject_cmake.gsl
- zproject_java.gsl
- zproject_known_projects.xml
- zproject_projects.gsl
- zproject_rpi.gsl
- zproject_travis.gsl
Solution: add support for an optional list of <add_config_opts> tags in <use> dependencies... and also in the <project> itself for completeness.
Example usage:
````
<use project = "libnutclient" test = "nut::TcpClient::TcpClient" header="nutclient.h"
prefix="nutclient"
repository = "https://github.com/networkupstools/nut">
<add_config_opts>--with-doc=skip</add_config_opts>
<add_config_opts>--with-dev=yes</add_config_opts>
</use>
````
> Problem: some (non-zmq) dependencies need customized CONFIG_OPTS

- zproject_autotools.gsl
- zproject_debian.gsl
- zproject_install.gsl
- zproject_redhat.gsl
Main problem: some daemons do not want the .cfg file 
Solution: add the inverse flag `no_config=1` to specify that the `$(main.name).cfg` should not be generated, built or distributed
> Add support for main "no_config" attr, and some minor fixes

- zproject_autotools.gsl
Solution: If there is a private class for a model add a private
switch to the models `make code` target.
> Problem: zproject doesn't tell zproto about private classes

- zproject_redhat.gsl
Solution: copy and adapt part of zproject_autotools.gsl
> Problem: installed API files not a part of rpm pacjaging

- zproject_redhat.gsl
Solution: do not mark api files as directories
> Problem: rpm build fails

- Makefile.am
- zproject_autotools.gsl
Solution: add -Isrc/ to CPPFLAGS; just in case for build-time generated headers (e.g. from templates) also add the builddir/include and builddir/src.
NOTE: This is about internal headers (implementation details of classes and APIs) as far as I've seen, so it makes little sense to expose them in include/ dir properly. But feel free to decide more authoritatively if any of those should be generated into another path; out of scope for this PR though :)
> Problem: some generated sources place internal headers into src/

- Makefile.am
- zproject_autotools.gsl
Reverts zeromq/zproject#861
Problem statement by @jimklimov is **not a problem**:
1. Internal headers *should* be placed into src/
2. As @bluca mentioned in the [comment](https://github.com/zeromq/zproject/pull/861#issuecomment-282019544), internal headers *should not* be placed into /include,  but that is **NOT** happening. There is nothing to be fixed!
3. No matter what, a cleanly generated project (i.e. no manual wiring) will never fail `make distcheck`.
The real problem @jimklimov was trying to fix with this PR was that one of our repos was failing `make distcheck` on his system. The reason why this repo failed is not because of zproject but because someone made manual changes to the wiring/includes. 
@jimklimov: If you provide a project.xml that would, after generation (without …
> Revert "Problem: some generated sources place internal headers into src/"

- zproject_autotools.gsl
> Problem: project-local CMake hook are not included

- zproject_autotools.gsl
Reverts zeromq/zproject#865 because it will break downstream projects (and is not fixing an error in the first place). See also #860.
> Revert "Problem: project-local CMake hook are not included"

- Makefile.am
- configure.ac
- zproject_autotools.gsl
Solution: detect it at configure time and redist optionally
Thanks to @aquette for persisting that PR #860 did introduce a bug.
> Problem: projects stopped EXTRA_DISTing Makemodule-local.am after PR#860

- zproject_debian.gsl
Solution: Fix paths for systemd bin service and timer on Debian
> Problem: systemd bin have issues on Debian

- zproject_autotools.gsl
- zproject_debian.gsl
- zproject_redhat.gsl
Solutions:
* generate configure.ac snippets for systemd service and timer .in templates, where available;
* add gitignores for such generated files;
* support systemd timer units (if sources are present) not only for BINs but also MAINs to be on par (redhat, debian)
Follow-up for PR #864 ...
> Problem: Improvements in PR#864 did not generate files from templates

- README.md
- project.xml
- zproject_autotools.gsl
- zproject_debian.gsl
- zproject_redhat.gsl
Solution: add the timer attribute and generate files and install snippets equivalently to the service attribute, both for MAIN and BIN objects.
Follows up on PRs #873 and #864 
Thanks to @karolhrdina for prodding me to continue on this :)
> Problem: recent support of systemd timers is not a first-class citizen

- zproject_autotools.gsl
Solution: zproject_autotools.gsl : fix delivery of bins/mains X services/timers in the makefile
Follow-up to PR #875 and hopefully nails the issue :)
> Problem: Makefile does not add timer/service for bins to _DATA var

- zproject_autotools.gsl
Solution: fix the copypaste artefact -- indeed only .in's should be in place for configure.ac, but either template or real file are needed/suffice for other rules
> Problem: Makefile recipes for timers/unit were only generated for .in's

- autogen.sh
- packaging/debian/rules
- zproject_autotools.gsl
- zproject_debian.gsl
Solution: call autogen.sh before building to generate the dummy
Follow-up to #860 et al
Improvement tested in our project - passed public Travis and private Jenkins + OBS
> Problem: Debian packaging misses src/Makemodule-local.am if not in SCM

- zproject_known_projects.xml
This PR adds support for https://github.com/zeromq/zdiscgo.
> Problem: we want to use zdiscgo

- packaging/debian/rules
- zproject_debian.gsl
Solution: define makefile-style targets to call or clean-up the autogen script within currently processed set of recipes rather than calling a $(MAKE) with an undefined makefile name ;)
Follow-up for #883
> Problem: debian/rules "autogened" should not call extra $(MAKE)

- zproject_android.gsl
- zproject_cmake.gsl
- zproject_java.gsl
- zproject_rpi.gsl
- zproject_travis.gsl
Solution: use the original spelling provided by project.xml script author, because git is case-sensitive about branch names.
> Problem: generated "git clone" commands lowercase the branch ("release")

- zproject_autotools.gsl
Solution: Add some complementary information
When using both autotools and systemd, since configure.ac is generated first
and checks for the actual presence of service file to list these in
AC_CONFIG_FILES directive, and since the generation of these service files is
done after the configure.ac generation, it results that systemd service files
generation are missing from configure.ac, and thus the files are not generated
from the template. A workaround is to call twice `gsl project.xml`, but it is
worth a fix.
> Problem: Generation of systemd service is missing

- zproject_travis.gsl
Solution: add a CI build run with GCC's Address Sanitizer enabled.
This compiler flag will make the unit test programs abort if it
detects errors such as out-of-bound memory access or use-after-free.
> Problem: lack of out-of-bound memory checks in tests

- configure.ac
- zproject_autotools.gsl
- zproject_travis.gsl
Solution: remake by producing a custom configure option
Follow-up on #892 
In any case, having this automated can be beneficial for not-only-travis test builds.
> Problem: current integration with ASAN can break CFLAGS

- configure.ac
- zproject_autotools.gsl
Also add messages to make ASAN and GCOV enablement more visible
Follow-up to #892 and #893
> Configure script: the flag type for ASAN is "enable", not "with"

- CMakeLists.txt
Add recently introduced block into its own recipes (see #895)
> Cleanup for zproject self-generation (Windows UWP)

- zproject_travis.gsl
Solution: DRY is good. Don't WET yourself (especially if manually). Use YAML references to define and maintain just once the list of dependency packages and their repos (e.g. OBSed ones from zeromq ecosystem).
Also made default builds docless (so no overhead of installing doc generation packages as well as running them), while a build with docs is handled separately - and earlier in the matrix chain, so overall the build does not wait for it alone to finish.
Example victim file: https://github.com/jimklimov/fty-proto/blob/test-yaml-refs/.travis.yml
> Problem: generated .travis.yml repeats too much

- zproject_autotools.gsl
solution: add a check for the bindings directory and include it if it exists (i think it exists always? but not sure)
this way make dist will include the bindings as part of the official distribution, rather than having to grap the source from GH (or other).
this may enable things like '--enable-binding=python|java|etc' which would install the relevant bindings too (future PRs).
> problem: makefile missing bindings directory inclusion for dist

- zproject_python_cffi.gsl
Solution: simply use ffi from cffi module
> Problem: all generated cffi bindings expects pyczmq

- AUTHORS
- zproject_python.gsl
So the current working directory gets restored even if that library isn't found.
This should fix issue #904.
> Add a try/finally around python loading libczmq

- zproject_python_cffi.gsl
Solution: reorganize a concept totally. Those are changes
* create Python package $(project.name)_cffi
* move definitions to one file
* add dlopen module for older approach
* add build.py to actually build extension module
* let __init__.py try native and fallback to dlopen version
Tested on czmq_cffi bindings
> Problem: cffi bindings are slow to import and require C parser

- zproject_cmake.gsl
Related to #907 
From different sources it seems that SOVERSION should be only one number(abi?) and VERSION should be major.minor.patch
http://pusling.com/blog/?p=352
https://cmake.org/pipermail/cmake/2012-September/051902.html
https://gitlab.cern.ch/dss/eos/commit/18ff0746ff4bc1263648fe3fdda79075ce262093
> Add VERSION property and fix SOVERSION value

- zproject_java.gsl
- zproject_java_lib.gsl
Solution: Make the template functionality match the basic idea from
the python bindings.
This addresses https://github.com/zeromq/zproject/issues/909
> Problem: JNI singleton methods aren't static

- zproject_travis.gsl
Solution: in ci_build.sh enable ASAN just for "this project", not for prereqs
> Problem: projects that rebuild prereqs can fail ASAN linking

- zproject_nodejs.gsl
Solution: use ?= comparator to account for the case where the
variable is not defined before dereferencing it
> Problem: NodeJS generation fails due to undefined dereference

- zproject_python_cffi.gsl
- zproject_redhat.gsl
Solution: after a bath, relax, cleaning, ... I have finished a spec file generation for python_cffi bindings. This is a part of my 😈 plan to have 🐍 (cffi) the first class citizen for zproject based projects.
Works reasonably well, see
https://build.opensuse.org/package/show/home:mvyskocil:branches:network:messaging:zeromq:git-draft/czmq
The only remaining problem are systems without python3 interpreter. I need to find a solution for them.
And yes, Debian is not supported.
🖌 : and yes. Second problem right now generated bindings works only with DRAFT build ...
> Problem: I woked up early today

- packaging/redhat/zproject.spec
- zproject_redhat.gsl
Solution: rearrange GSL code to not add the lines, regenerate zproject
Follow-up for #917, should also fix the travis builds broken by merging that PR (due to not regenerated zproject)
> Problem: needless blank lines added to re-generated specfiles

- packaging/redhat/zproject.spec
- zproject_redhat.gsl
Solution: fix the apparent typo/experimentation that was committed
Follow-up for #917
> Problem: in specfiles, autogen.sh is no longer required?

- zproject_python_cffi.gsl
- zproject_redhat.gsl
SOlution: split python2/python3 bindings to separate spec file, so we can
better control who is going to use it
see https://build.opensuse.org/package/show/home:mvyskocil:branches:network:messaging:zeromq:git-draft
> Problem: build of czmq fails on platform w/o python3

- zproject_debian.gsl
Solution: parse DEB_BUILD_OPTIONS and the OBS config for the
python_cffi macro and build the bindings only if it's set.
This is similar to what RPM does, but it still creates the emtpy
packages.
Although it is possible to generate dynamically new binary packages
at build time for Debian, it's very hacky and dirty so it's better to
avoid it unless absolutely necessary.
> Problem: Python CFFI only works with DRAFTS on CZMQ

- packaging/obs/_service
- zproject_debian.gsl
- zproject_obs.gsl
Solution: use dh_installman for manpages instead of dh_install, so
that the build options and profiles are automatically taken into
account.
Also regenerate.
> Problem: Debian nodoc build fails due to missing manpages

- zproject_redhat.gsl
Solution: fix paths in redhat packaging
@bluca - I did not find a similar section for Debian packaging. I'll let you to handle it ;-)
> Problem: python package name has underscores only since f901cb9

- zproject_redhat.gsl
Solution: use dashes in package names
> Problem: python2-zm-proto_cffi is legal, but weird package name

- packaging/redhat/zproject.spec
- zproject_python_cffi.gsl
Solution: use absolute import for dlopen/native
> Problem: can't import cffi bindings in python3

- zproject_python_cffi.gsl
Solution: don't output setup.py if there are no python bindings to
fix regen with target *
> Problem: regeneration fails with no binding

- CMakeLists.txt
- zproject_python_cffi.gsl
Solution: let the upper module contains the definitions of all dependant ones.
TL;DR;
The original error code was
TypeError: initializer for ctype 'struct _mlm_client_t *' appears indeed to
be 'struct _mlm_client_t *', but the types are different (check that you are
not e.g. mixing up d ifferent ffi instances)
The point is that every $(project) defines own ffi instance, which sadly can't
be mixed in one function call.
client = mlm_cffi.lib.mlm_client_new ()
msg = zm_proto_cffi.lib.zm_proto_new ()
zm_proto_cffi.lib.zm_proto_recv (msg, client)
zm_proto_recv works with two declarations of mlm_client_t and thus fails. The
problem is that every cffi module must be self-contained, so all types must be
resolved. Proposed solution is kind of static linking, but it have two advantages
1. following …
> Problem: you cannot mix two ffi instances in one call

- zproject_python_cffi.gsl
Solution: generate definitions to _cdefs.inc files, which are embeded in cdefs.py via file.slurp command. This makes nested dependency chains working well.
> Problem: f232164 does not work for third level of dependencies

- zproject_class.gsl
- zproject_class_api.gsl
**Problem: Cannot define private methods in the API**
I would like to be able to define methods as private, in public classes.
The idea would be to have something package-private methods, like in Java. 
**Solution: Write private methods into project_classes.h**
The XML definition would look something like this:
```
<class name="my public class">
<method name="public method">
Does stuff anyone is allowed to do
<return type="nothing"/>
</method>
<method name="private method" private = "1">
Does stuff only part of the library is allowed to do
<return type="nothing"/>
</method>
</class
```
> Allow private/protected methods in public classes

- packaging/debian/copyright
- zproject_debian.gsl
Solution: fix it so that empty lines in the license block are changed
to a space and a dot as per policy and regenerate
> Problem: debian copyright output is in wrong format

- zproject_vagrant.gsl
solution: removing old [python] deadsnakes apt repo, defaulting mem to 1024 from 512
> problem: vagrant gsl contains out of date repo and too little memory for newer versions of zmq

- src/Makemodule.am
- zproject_autotools.gsl
- zproject_travis.gsl
Solutions: several improvements for `selftest-rw` directory support, and to re-run memcheck verbosely if it originally failed in travis.
> Problems: Selftest can fail due to dirty previous runs

- zproject_skeletons.gsl
Solution: zproject_skeletons.gsl updated with example pattern on using SELFTEST_DIR_R[OW] to create the filename strings.
> Problem: string concatenation for selftest dir usage

- zproject_travis.gsl
zproject_travis.gsl : inability to make the CCACHE_DIR precludes its usability. Also avoid naming this path in two different ways that can diverge in the future.
> Problem: CCACHE_DIR scripting can be improved

- zproject_python_cffi.gsl
Solution 1: Create a cffi C library which wraps czmq destroy methods with ffi.gc compatible method signatures
Solution 2: Generate lean wrapper classes which are correctly GC'd by python using the destructors wrapper library. Currently only strings are and custom c_types are supported as parameters.
> Python cffi binding does not generate wrapper classes

- zproject_python_cffi.gsl
__Problem:__ If we are going to call `find_library()`on line 224 then we must define it first or a NameError could be raised at runtime.
__Solution:__ `from ctypes.util import find_library`  https://docs.python.org/3/library/ctypes.html#finding-shared-libraries
> from ctypes.util import find_library

- zproject_python_cffi.gsl
__Problem:__ The current compatibility code breaks Python 3 porting guidelines by using version detection instead of feature detection.  It would for instance, would fail under Python 4 and above by treating them as if they were Python 2..
__Solution:__ Follow the Python 3 porting guide best practice: __Use feature detection instead of version detection__.
https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection
> Py3: Use feature detection, not version detection

- zproject_python_cffi.gsl
Solution: Check if the method name equals a known python 2 keyword and escape it with "_py" to prevent syntax errors.
> Problem: cffi binding is erroneous if method name equals keyword in python 2

- zproject_skeletons.gsl
because of "gsl/4 M: Generating skeleton for include/agent.h
(zproject_skeletons.gsl 77) Can't open output file: include/agent.h
"
Solution: create include diretory together with src
> Problem: Cannot generate new project with agent

- zproject_redhat.gsl
Solution: remove commented out spec macro. RPM builds parse commented
out lines too, so macros should not be left in comments.
> Problem: RPM builds fail on Fedora Rawhide

- zproject_autotools.gsl
Solution: in zproject_autotools.gsl add .cc support if project.use_cxx is enabled
> Problem: lcov recipe only supports *selftest.c

- zproject_skeletons.gsl
Solution: be nice in generated self-test skeleton code, and asset the zactor variable (people do copy-paste the snippets)
> Problem: zactor_new() return value unchecked

- src/Makemodule.am
- zproject_autotools.gsl
- zproject_bench.gsl
For a project that links with OpenSSL, I need to add
--sigill-diagnostics=no to the valgrind command line to paper over
OpenSSL triggering and handling SIGILL on arm (more details here:
https://bugs.kde.org/show_bug.cgi?id=331178). This patch adds support
for a VALGRIND_OPTIONS make variable, which can be set in
Makemodule-local.am.
Signed-off-by: Michal Marek <MichalMarek1@eaton.com>
> autotools: Introduce VALGRIND_OPTIONS variable

- zproject_skeletons.gsl
Solution: make the documentation shorter, declare them before each selftest
method, convert to macros, so no dynamic string allocation or different
declaration for C and C++ are needed.
> Problem: SELFTEST_DIR declarations pollute manual pages

- packaging/debian/rules
- zproject_debian.gsl
Solution: it does not suffice to just `export DEB_BUILD_OPTIONS=parallel=8` or `MAKEFLAGS=-j8` or call `dpkg-buildpackage -j8` ... the `dh` command in the `debian.rules` file must have the `--parallel` flag as well - according to my experiment and to https://www.linuxquestions.org/questions/linux-software-2/parallel-jobs-with-dpkg-buildpackage-4175502264/
> Problem: debian packages do not build in parallel

- zproject_skeletons.gsl
Solution: document back the copy-pasteable comment about constructing filename variables in tests
> Problem: PR #982 removed usage pattern for SELFTEST_DIR_R[OW]

- configure.ac
- src/Makemodule.am
- zproject_autotools.gsl
When building in the source directory, the check target prints the
following warning:
make[2]: Circular /home/michal/GIT/zproject/src/zproject_selftest <- /home/michal/GIT/zproject/src/zproject_selftest dependency dropped.
Instead of a runtime check, use an automake conditional and disable the
rule completely when building in the source directory.
> autotools: Fix Makefile warning with make check

- zproject_redhat.gsl
Solution: have a dependency on python, not python3
> Problem: can't install python3 cffi bindings on openSUSE

- zproject_java_lib.gsl
Solution: add interface to list of Java keywords, which are handled by zproject generator
> Problem: Zsys.java contains manually renamed method

- zproject_redhat.gsl
Solution: distinguish python vs python3 build conditionals for rpmbuild
> Problem: there's no python3 on older rhels

- zproject_python_cffi.gsl
Solution: handle native python types for a function with two arguments (self
and zlist_t **) as zproto's strings. This allows usage of native python types.
cc: @sappo please review the approach carefully. I am not sure I got intended semantics of *generated* Python bindings well. With this patch I can simply pass high level python structures to zproto's strings field.
> Problem: python cffi: generated methods for strings are not Pythonic

- src/zproject_selftest
Solution : zproject_selftest : a required distclean during "make check" removes the parent Makefile and config.status used in the test - restore them
> Problem : "make check" fails

- zproject_python_cffi.gsl
Solution: set zlist_autofree, so zlist OWNs its content and Python garbage
collector does not destroy C lists.
> Problem: python cffi: garbage in zlist_t

- Jenkinsfile
- zproject_jenkins.gsl
Solution: Jenkinsfile zproject_jenkins.gsl : typo fix - DO_BUILD(_WITH)_DOCS - mismatched the build arg and the tested variable name
> Problem: typo in pushed zproject_jenkins.gsl

- Jenkinsfile
- zproject_jenkins.gsl
Solution: groovy build args are available, matching envvars are not populated on the first 1-2 runs of a MultiBranch Pipeline, a known deficiency in Jenkins. So instead of when{env...} we should check when{expression...}
> Problem: first run of a newly discovered MBP does not see build args

- Jenkinsfile
- README.md
- project.xml
- zproject_jenkins.gsl
Solution: Add optional support for `cppcheck` utility to validate C/C++ codebase; feature is disabled by default since this requires a third-party tool on the Jenkins worker instance.
> Problem: Jenkinsfile does not cppcheck

- zproject_class_api.gsl
Solution: add support
This also fixes a variable name which caused a crash when aborting due
to an unsupported API state.
> Problem: no support for "deprecated" API state

- zproject_ruby.gsl
Solution: DRY the FFI attachment of draft and deprecated functions using
two Ruby helper methods:
* ProjectName::FFI.attach_deprecated_function()
* ProjectName::FFI.attach_draft_function()
> Problem: Ruby bindings are very noisy around draft/deprecated functions

- zproject_class.gsl
Visibility attribute "hidden" is not supported by Windows executables.
Signed-off-by: Pedro Luis Castedo Cepeda <pedroluis.castedo@upm.es>
> Fix Cygwin autotools build 'visibility attribute not supported' error

- zproject_ruby.gsl
It assumes that all the stable functions are provided by an installed
library. But this assumption breaks as soon as the API contains a new
stable function that is not available in an already installed version of
that library. (See zeromq/czmq#1795)
Solution: gracefully handle any function that is not available in the
installed library, not only draft/deprecated ones. A placeholder
method is defined that will simply raise NotImplementedError.
> Problem: Ruby bindings are fragile

- Jenkinsfile
- zproject_jenkins.gsl
Solution: For builds where temporary dirs are spawned to unstash and build/test code, deleteDir() after successful previous steps (bad builds should remain available for postmortem; feature is optional via build parameter)
> Problem: workspaces after build consume Jenkins storage

- Jenkinsfile
- zproject_jenkins.gsl
Solution: wipe it (if present) before prepping
Note: This nuance proved to be quite a space-hog (unconstrained disk-space leak over several rebuilds in same workspace).
> Problem: tmp/ stashed and unstashed in Jenkins

- Jenkinsfile
- src/Makemodule-local.am
- src/Makemodule.am
- zproject_autotools.gsl
- zproject_jenkins.gsl
Solution: rely less on `abs_*` in build recipes, and hack the `LD_LIBRARY_PATH` for tests under relocated build tree. Pathname changes are a required collateral damage of faster parallel testing without conflict of the test runs.
> Problem: Jenkins builds in sub-dirs do not work when dir name changes

- Jenkinsfile
- README.md
- project.xml
- zproject_jenkins.gsl
Solution: If the project is not marked stable, default to not testing non-DRAFT stages. There is no support in build recipes for the --enable-drafts option in this case anyway.
> Problem: Jenkinsfile tests stable build even when there is none

- Jenkinsfile
- zproject_jenkins.gsl
Solution: zproject_jenkins.gsl / Jenkinsfile : clean up tmp/ before cppcheck
> Problem: Jenkinsfile cppcheck takes too long

- zproject_travis.gsl
Solution: we have a specially defined environment and BUILD_TYPE to test docs generation; do not require it explicitly always
> Problem: one stage of Travis tests enforces --with-docs=yes

- README.md
- project.xml
- zproject_jenkins.gsl
Solution: Allow project authors to generate a Jenkinsfile that runs self-tests sequentially, while they think of a better fix. This takes more wallclock time, but avoids port conflicts etc. in the same environment. Note that such ability to fail can expose potential resilience problems for production builds too.
> Problem: Jenkins tests fail with hardcoded ports in codebase

- CMakeLists.txt
- zproject_cmake.gsl
Problem: It is not possible to build shared and static builds using the zproject_cmake template, (Or a static build ...)
Solution:
The changes create a CMakeLists.txt file very similar to the one libzmq uses.
Example: Features added to czmq
adds options CZMQ_BUILD_SHARED and CZMQ_BUILD_STATIC (both default on)
MSVC: create static and shared libs with the name: czmq-v120-mt-s-4_0_3.lib, czmq-v120-mt-4_0_3.dll
MSVC: export CZMQ_STATIC flag
Generate a valid CZMQ_VERSION variable
UNIX: shared: generate versioned so_name
UNIX: static: generate standard unversioned name
export include_dirs and compile flags to depending projects
I hope this does not break anything. This change was tested with czmq on windows and linux.
> Allow static/shared builds for cmake generator similar to libzmq CMakeLists.txt

- CMakeLists.txt
- zproject_cmake.gsl
Because of compatibility issues, versioned DLL library naming had to be removed.
Tested on Linux and Windows.
> Removed versioned library naming

- Jenkinsfile
- README.md
- project.xml
- zproject_jenkins.gsl
Solution: option use_test_retry>1 can help proceed with development while we figure out how to make selftests robust in all circumstances
> Problem: some tests fail randomly

- Jenkinsfile
- Jenkinsfile-deploy.example
- README.md
- project.xml
- zproject_jenkins.gsl
Primary use-case is speed up of packaging, using a tarball with pre-created doc files along with the git archive. Either way, this detail is implemented (or not) on the Jenkins side by a particular deployment admin.
Also do cppcheck in parallel to other tests, there is now little reason to start with it (and its long lag, for big codebases).
> Support providing dist tarballs to Jenkinsfile publish helper

- zproject_autotools.gsl
Solution: restore the default to enable all optional dependencies if
they are available to avoid backward incompatible change
This caused a regression in czmq - while in the previous version running ./configure by itself enabled the optional dependencies, now it doesn't anymore
> Problem: autoconf optional deps changed to default off

- zproject_python_cffi.gsl
Solution: change absolute utils import to relative (works in 2.7 and 3+)
> Problem: python_cffi bindings not python3 compatible

- zproject_redhat.gsl
Solution: gcc run from setuptools failed, however the same command
copy&pasted to shell passed. It is most likely related to bad quoting of
~ in python3 port of setuptools. So main project include path was broken
in a compiler, however shell quote (\~) was fine.
As a workaround spec file now makes symlinks for libdir and includedir,
so paths have only boring and safe ascii letters. Generated pkg-config
file now points to local links and as a result, python3 bindings are now
built in our OBS instance.
> Problem: build of python3 bindings fails if path has ~

- zproject_class_api.gsl
Solution: load API models in /usr/local and /usr. Order of preference is
1. current dir for git snapshots
2. /usr/local/share/ for results of make install
3. /usr/share for installed rpm or Debian packages
> Problem: inconsistency between installed czmq and git snapshot

- zproject_autotools.gsl
- zproject_class_api.gsl
- zproject_python_cffi.gsl
- zproject_redhat.gsl
Solution: do not rely on random git snapshot when generating bindings.
Instead generate api/python_cffi.slurp and install it together with api
files. Then slurp the file from following locations
1. ../$project/api/ to use git snapshots
2. /usr/local/share to use result of make install
3. /usr/share tu use installed rpm or debian packages
This ensures consitency between installed czmq-devel and generated
bindings.
> Problem: python cffi incompatible with system installed czmq

- Jenkinsfile
- zproject_jenkins.gsl
Solution: tarball the test logs (and trace-files); throw the procesed exception up the stack so error is visible (and e.g. a retry{} happens)
> Problem: Jenkinsfile only archves one test-suite.log, and hides the fault

- zproject_python.gsl
Generate the setup.py in the binding/python (each project should remove setup.py at the root)
Add dependencies, licencse, version (like for cffi)
> Better python setup.py generation

- zproject_autotools.gsl
Solution: partially revert d27b30fea702341df3582f762277bda9b5befe78
Never ever mangle man1 documents, they must be the same as names of
mains itself, otherwise it will be totally confusing for end users.
> Problem: can't build rpm due not found man1 page

- zproject_class.gsl
Solution: add subtest parametr to _private_selftest function, which
allows us to distinguish one test, while not exporting private
classes symbols anywhere in resulting .so file. The $ALL name is for
compatibility with older zprojects, so -t private_classes option works
the same way as before.
> Problem: can't run test for one private class

- zproject_class.gsl
The generated code expects that czmq pulls in a few headers and macro
definitions. This is a minimal fix for the generated selftest file in
C++ mode.
> Allow projects without czmq dependency (part 1)

- zproject_vs20xx.gsl
Building on windows by calling build.bat fails as it tries to build
projetc configurations which do not exists in the visual studio solution
or project files. This commit changes the configuration names in the genereated
build.bat file to be in sync with the visual studio solution and project
file.
> fix configuration names in build.bat

- zproject_vs20xx.gsl
When compiling the visual studio solution with visual studion vs20xx,
the compiler complains about the missing symbol *_private_selftest
(i.e. for czmq project, czmq_private_selftest).
Other generated build systems do contain the source of the
private_selftest function (for draft builds).
This commit adds the private_selftest source file to the visual studio
project file. Please note that the generator for the visual studion 2008
already does include the private_selftest source file into the generated
project file.
> include private selftest source in vs project file

- zproject_class.gsl
When building on windows with visual studio, source files are
compiled using the c++-compiler. So all exported symbols need
to be enclosed by an extern "C" {} to force c-linkage (which
almost all exported symbols do already).
However the private_selftest function, which gets exported in
project_library.h (i.e. czmq_library.h) when building
in draft mode, is missing an extetn "C".
This commit encloses the private_selftest function declaration in an
extern "C" block to also force c-linkage for that symbol.
> force c-linkage for private_selfttest function

- zproject_vs20xx.gsl
when loading the generated solution file in visual studio, it gets
rewritten by visual studio, replacing solution build configurations
and platforms.
This commit tries to improve generation of visual studio files by
- generating unique subproject guids using the project name hash
- generating project configuration platforms for each subproject
- using tabs instead of spaces for indentation´
fixes #1055
> generate valid visual studio solution file 

- zproject_python_cffi.gsl
Solution: generate them (the same way as Python bindings)
> Problem: python cffi class constants not available

- zproject_autotools.gsl
Problem : private headers are not listed in EXTRA_DIST, so make distcheck could not find them.
Solution: add them 
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
> Problem: make distcheck failed about missing private headers

- builds/cmake/Modules/ClangFormat.cmake
- builds/cmake/ci_build.sh
- src/Makemodule.am
- zproject_autotools.gsl
- zproject_cmake.gsl
- zproject_travis.gsl
Not enabled by default, but can be uncommented in the generated file (for teams who do not use cmake and so have its files removed from the tree).
>  clang-format-check : provide an autotools-only implementation for travis users

- packaging/debian/copyright
- project.xml
- zproject_debian.gsl
Solution: make the project.starting_year a configurable value
> Problem: debian copyright is always from 2015

- zproject_class.gsl
For GCC 4.0+, explicitly set the default visibility of exported symbols,
so that it is possible to build shared libraries with
-fvisibility=hidden.
> Make it possible to build code with -fvisibility=hidden

- doc/Makefile.am
- zproject_autotools.gsl
Solution:
* ensure making the directory for generated txt/doc files for mains
* tell `xmlto` to output generated files into target (not current) dir
* Regenerate zproject
> Problem: building manpages for mains in nested dirs 

- Jenkinsfile
- Makefile.am
- configure.ac
- zproject_autotools.gsl
- zproject_jenkins.gsl
* sanitize configure script and Makefile support for pedantic compile-time error-checking (less hardcoding, less conflict with random compilers, use the available configurability)
* allow use (or disablement) of the pedantic checks in Jenkins, similar to how Travis does both variants
> Sanitize --enable-Werror support

- README.md
- README.txt
- zproject.gsl
- zproject_autotools.gsl
Solution: let configure a project to install its headers into includedir/projname instead
> Problem: headers always dumped into main includedir

- Jenkinsfile
- README.md
- project.xml
- zproject_jenkins.gsl
Solution: add an option to keep a `CCACHE_LOGFILE` for postmortems in a workspace (off by default)
> Problem: hard to track usage of CCACHE in Jenkins builds

- builds/cmake/Config.cmake.in
- zproject_cmake.gsl
Solution: add this functionality
by default, all dependencies are treated as `PUBLIC` because in zproject they are not handled separately at the moment. Another limitation is that the users maybe want to modify the Config.cmake.in file. Here we should allow the inclusion of a local file - just like `CMakeLists-local.txt`...
tested with czmq and zyre
> Problem: zproject does not generate cmake package configs

- Makefile.am
- zproject_autotools.gsl
Solution: add the line to zproject_autotools.gsl and update the zproject
this fixes an issue introduced by #1088 and observed here: https://github.com/zeromq/czmq/pull/1927
> Problem: Config.cmake.in is missing from the EXTRA_DIST files

- .gitignore
- zproject_git.gsl
- zproject_travis.gsl
Solution: if a project.use_cxx is true, tell travis to test as "cpp"
Note: the difference seems cosmetic at the moment, the same GCC toolkits are installed. But still, this is cleaner :)
> Problem: Travis always tests code as "c"

- zproject_class.gsl
Solution: Restore the pre-Feb2018 coding pattern (ease regeneration of less dynamic projects) and retain the benefits of that patch (do not require builds with czmq headers).
CCing @bluca @michal42 whose work is reverted here (note especially Luca's patch - was the original cause a syntax curiosity of MacOS compilers, or a logical error in the string comparison)?
> Problem: ZMQ-style compact streq() replaced by strcmp()==0 monstrosity

- zproject_travis.gsl
Solution: zproject_travis.gsl : autotools variant of clang-format-check needs prereq packages installed (if coming from OS or prebuilt from source)
> Problem: Travis sometimes fails clang-format-check with autotools

- Jenkinsfile
- README.md
- project.xml
- zproject_jenkins.gsl
Solution: add a do_cleanup_after_failed_build option (via project.xml and interactive build args)
> Problem: failed Jenkins builds unconditionally eat disk space

- project.xml
- zproject_jenkins.gsl
Solution: bump default timeout to 30 minutes, to cater for slower/overloaded Jenkins CI servers (and match Travis CI defaults)
> Problem: zprojectized components sometimes time out in Jenkins

- zproject_skeletons.gsl
In the detail : zmalloc function does not make sense in a project which not using czmq
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
> Problem : a project.xml without czmq dependency is not buildable

- zproject_skeletons.gsl
1) **Provided solution does not work**
Even if we pretend for a moment, that declared "problem" is a problem, then this pull request does not provide a working solution:
https://gist.github.com/karolhrdina/b3b702d529d66502698dd509ea1906e8
This gist has two files, `project.xml` -  a minimal zproject xml without czmq dependency, `output` - output of doing gsl project.xml; ./autogen.sh && ./configure && make, which fails as seen.
2) **Provided 'Problem' statement is not a problem**
> zproject is a project that makes it cheaper to build other projects that use ZeroMQ.
^^^ is a quote from Hintjens himself in a article http://hintjens.com/blog:79 presenting zproject to the public for the first time. 
`zproject` is not supposed to work without `czmq`; This fact is obvious in every part of gsl …
> Revert "Problem : a project.xml without czmq dependency is not buildable"

- Jenkinsfile
- README.md
Regen the doc; reconcile the new Jenkins timeout with what the codebase itself uses.
Follows up on omissions from PR #1097 - sorry about those.
> Fix zproject selfcheck on Travis

- packaging/debian/control
- packaging/redhat/zproject.spec
- zproject.gsl
- zproject_debian.gsl
- zproject_obs.gsl
- zproject_redhat.gsl
Use-case for the problem: a project declares several `class` tags but all of them are `private="1"`, and a `main` with the binary (daemon) which is of practical interest to consumers. In practice, current zproject only packaged libraries if there is at least one non-private class. As a result, the installed binary does not have the libs it was linked against, and could not run.
Note that for some time now, at least on some platforms, the difference of public/private is not "exportedness" and so accessibility of library symbols, but their visibility/scope (so "private class" libs are usable if a binary knows what to ask for).
This PR adds packaging of libraries if either there are public classes, or (newly) if there are some classes and mains.
Note that `bin` tags are not consulted here, …
> Fix packaging of libs if we deliver mains

- zproject_class.gsl
- zproject_projects.gsl
Solution:
if project is not czmq or does not depends on it
1. move `__WINDOWS__` definition to `_library.h`
2. include basic ANSI headers mandatory for generated code in private `_classes.h`
3. include common idioms streq/strneq/zmalloc in `_classes.h`
4. fail if `actor` is specified, but `czmq` is not in the dependency list
cc: @bluca @karolhrdina @geraldguillaume
references: #1101
references: #1102
references: #1105 
This is leaner and smaller version of previous attempt. Tested manually with minimal project.xml(s) and with czmq.
> Problem: implicit dependency on czmq

- zproject_class.gsl
Solution: fix a guard for bool definition, skip it for czmq and
dependent projects
> Problem: czmq prelude bits are pointless in czmq itself

- zproject_class.gsl
Solution: when generating the internal classes draft definitions for
non-draft builds, also add global constants.
> Problem: public global draft constants not added to internal build

- zproject_class.gsl
- zproject_debian.gsl
Solution: shuffle the pretty blanks to be inside conditionally generated blocks, minimize changes in regenerated projects
> Problem: recent changes add blank lines

- README.md
- project.xml
- zproject_projects.gsl
Solution: verify that classes and actors are not named same as the project, their headers should differ too
Note: gsl abort() currently seems flawed in not returning a non-zero exit code, but that is a separate issue
Note: the initial issue was that we saw duplicate header filenames listed in `include/Makefile.am` for common list and draft additions. Digging into the issue produced this fix.
> Problem: header files listed twice confuse "install"

- builds/check_readme/ci_build.sh
- builds/cmake/ci_build.sh
- tstgenbld.sh
- zproject_android.gsl
- zproject_cmake.gsl
- zproject_docker.gsl
- zproject_git.gsl
- zproject_java.gsl
- zproject_nodejs.gsl
- zproject_rpi.gsl
- zproject_travis.gsl
Solution: avoid potential conflicts and simpify gitignore maintenance by dedicating a tmp-deps subdirectory for the checkout and build of dependency components.
Note: I tested this with a few projects that have Travis for autotools, and ported the fix but not tested for CMake and for bindings. One example is at https://github.com/42ity/fty-example/pull/24/files
> Problem: dependencies checked out into workspace root

- zproject_gyp.gsl
- zproject_java.gsl
Indeed, some bindings generators expected additional code to be present in specific directories obscured by numerous `..` references. These fixes should help reduce such occurrences, iteratively.
> Fix some fallout from #1113

- .gitignore
- ci_build.sh
- zproject_class_api.gsl
- zproject_gyp.gsl
- zproject_java_msvc.gsl
- zproject_nodejs.gsl
- zproject_travis.gsl
The `check_zproject` script verifies that an expected set-up of a developer workstation includes dependency checkouts in proper locations (into same parent dir as the checked project itself). Thus, it should not use `tmp-deps/` after all.
Also, generated projects' code should not refer to `tmp-deps/` either - if the dependencies' files are to be used directly without a checkout, it may be an unfortunately intimate type of dependency, but one that should be reproducible in a casual developer's environment manually per README instructions, etc.
> Clean up some more fallout from #1113

- zproject_class_api.gsl
Solution: Support stable=0 as state=draft and stable=1 as state=stable, and warn that project.xml should be updated into a proper definition of the state.
> Problem: Some projects use stable=0/1 with unexpected results

- README.md
- project.xml
- zproject_travis.gsl
Solution: avoid the need to keep up manually customized travis.yml bits
in projects that chose to avoid CMake by making the clang-format related
options for Travis CI tests configurable (defaults match current state
of zproject).
Also this PR adds support for `allow_failures` block to report style mismatches
in a manner non-fatal for the build.
> Problem: manual selection of clang-format in travis.yml

- zproject_autotools.gsl
Solution: leave the Requires: field empty if the correct name cannot be
found, otherwise pkg-config will fail and error out.
See: https://github.com/zeromq/czmq/issues/1944
> Problem: non-existing pkg-config metadata set if not found

- README.md
- project.xml
- zproject_travis.gsl
Solution: add an option to generally skip it, but run it in a special test case allowed to fail (2) as a project approaches maturity
> Problem: travis recipe allows to only do(1) or skip(0) distcheck

- zproject_qt.gsl
Solution: If there's a class with the same name as the project
choose another Qt project name to resolve the conflict.
> Problem: Qt-Binding fails to compile if a class name == project name

- zproject_java.gsl
when a function return sockish data type, it must be casted to (jlong) (intptr_t) like any other pointers, otherwise it can lead to unusable handle, I experienced this on android armv7 but not on armv8.
Only zpoller->wait() was affected.
> (JNI) sockish pointer must be casted to (jlong) (intptr_t)

- configure.ac
- packaging/debian/zproject.install
- src/Makemodule.am
- zproject_autotools.gsl
a redo of #1120 
solution: modify zproject_autotools.gsl to provide basic configure flags for python bindings and drop an "make bindings" option in src/Makemodule.am when a project is created.
(some day i will learn to rebase properly... old bad habits die hard)
> problem: zproject missing a way to configure/enable/install language bindings

- zproject_java.gsl
- zproject_java_lib.gsl
JAVA: Zconfig.remove is not correctly generated.
JNI: Corresponding jni native function return and hazardous value.
JAVA: If a function always return 0 it should return void.
Solution:
Fix java binding generator.
> Zconfig.remove is not correctly generated.

- zproject_redhat.gsl
Solution: remove brackets around the versions, they are illegal
in RPM packages
> Problem: syntax error in spec dependency format

- zproject_java.gsl
Solution: Android already ship with its own lib extractor so there's no need to use NativeLoader.
> Problem: NativeLoader fails on android 6

- README.md
- zproject_known_projects.xml
Solution: change libcurl dependency to the nss implementation. This
links to nss for TLS support, which is licensed under the MPL and so it
is compatible.
OpenSSL is not compatible with the GPL, which could cause issues for
GPL-licensed programs that want to use CZMQ with libcurl.
@somdoron FYI https://curl.haxx.se/legal/licmix.html
> Problem: CZMQ is linking with OpenSSL

- CMakeLists.txt
- zproject_cmake.gsl
Solution: Use a different path for each tool
Still an issue though, the `src/platform.h` is only get deleted when generating cmake but after that, if I run autotools and only recompile cmake build the file doesn't get deleted.
Any suggestions?
> Problem: cmake override autotools platform.h

- README.md
- zproject_known_projects.xml
It is actually only supported at the project level.
Solution: make libmicrohttpd use a repository instead of a tarball
> Problem: tarball is not supported at known project level

- README.md
- project.xml
- zproject_travis.gsl
The former was missing (only the script was generated) and the latter was imposed regardless of project readiness.
> Travis options for checking zproject and ABI compliance

- zproject_debian.gsl
Solution: fix path to match other units (/lib)
TODO: Honor configured @systemdsystemunitdir@ somehow?
> Problem: timer units installed into /usr/lib

- zproject_autotools.gsl
Started out as investigation for https://github.com/42ity/fty-metric-cache/issues/32 (which proved to no longer be a valid issue).
> Clarify some processing around main/no_config flag

- zproject.gsl
- zproject_docker.gsl
When generating a Dockerfile, the docker target assumes the project code is in the repository
`git://github.com/zeromq/$(project.name:c).git`
It should rather use the repository defined in the `<project>` tag in project.xml.
In order to generate a sane Dockerfile when the repository is not set in the project tag, we set it to
`https://github.com/zeromq/$(project.name:c)`, i.e. using HTTPS instead of SSH protocol.
> Problem: docker target doesn't use project repository.

- zproject_python.gsl
The only reason to regenerate setup.py is to update changes in project name, version and other project metadata. Some bindings may need more complex setup configuration than provided by the generator, so it makes more sense to only regenerate a separate file containing project name, version, etc. and read this file from within setup.py
> Problem: The python target regenerates setup.py

- zproject_cmake.gsl
Findlibzmq.cmake doesn't work out-of-box on Win32.
libzmq dll/lib built with MSVC is named using the Boost convention(something like libzmq-mt-4_3_1.lib, libzmq-mt-4_3_1.dll): https://github.com/zeromq/libzmq/blob/master/CMakeLists.txt#L1147-L1173
So find_library (LIBZMQ_LIBRARIES NAMES zmq HINTS ${PC_LIBZMQ_LIBRARY_HINTS}) will not work.
This patch tries to solve the `libzmq not found` error on Win32 with CMake:
https://github.com/zeromq/czmq/issues/1972#issuecomment-484842328
https://github.com/zeromq/czmq/issues/2004
> Problem: Findlibzmq.cmake doesn't work on Win32

- zproject_python_cffi.gsl
Solution: if the api says the argument is a reference create a ** pointer to it
> Problem: python_cffi binding can't handle double pointers

- zproject_travis.gsl
* zproject_travis.gsl : default distro should match the one specified in matrix tests to minimize the surprises
End-users of zproject are still free to define a specific distro, or comment away and use Travis CI default. But we found it confusing to have half the tests fail due to new compiler warnings, and the other half pass because they are on another compiler by default :)
> Problem: code tested in different distros, confusing results

- README.md
- project.xml
- zproject_travis.gsl
* zproject_travis.gsl : add shadow compilation (optionally non-fatal) with modern GCC and/or CLANG versions
Allow developers to prepare their codebase for newer OSes with their newer compilers.
Even with old compilers in place for production builds, the warnings and suggestions to improve code emitted by the newer ones do still bring benefits and help reduce practical errors in the codebase.
> Problem : outdated coding patterns come as a surprise with new compilers

- README.md
- project.xml
- zproject_travis.gsl
For some projects it is a problem, since the new distro brings a newer compiler and its warning become fatal for CI (see also #1176) ;)
This PR adds an ability for `project.xml` author to specify which distro should be used, and this impacts which package source for OBS-built zeromq stack would be used (unless the project wants to build everything from sources... as our forked one does...)
If nothing was specified, it should still specify "xenial" and corresponding "ubuntu16" repos.
> Problem : default travis dist is hardcoded (xenial)

- README.md
- README.txt
- zproject.gsl
- zproject_autotools.gsl
- zproject_debian.gsl
- zproject_redhat.gsl
- zproject_travis.gsl
Should solve the woes of #1174
Note that not all projects require it on one hand, and not all projects survive the new "xenial" distro out of the box on another, hence the toggle.
Note: as comments say, for packaging (BuildRequires etc) and Travis this might hardcode usage of gcc-4.9 even if your current distro offers a newer one by default. Where possible, I tried to make this extensible (e.g. requiring "at least 4.9.0" in packages, and checking for practical features in `configure.ac`).
> Ensure at least GCC-4.9 if a project needs real C++11 support

- zproject_java.gsl
Solution: Upgrade to the most recent version
> Problem: Gradle wrapper version 5.0 has a major security vulnerability

- zproject_java.gsl
Solution: Using System.loadLibrary you can load the same library as many
times as you like because subsequent calls will be ignored. But this is
only true if you try to load the same library from the same file.
Because the NativeLoader copies the jar-packaged library to a random
directory in the temp dir we're loading the same library from different
files which causes the java process to abort fatally.
Therefore we will load the libraries with our own static library loader
wrapper that will only call the NativeLoader if that library has not
been load previously. And because we generate the wrapper in every
zproject generated jni libraray the jvm will simply pick up the first
one it encounters hence there's no need to have a common dependency
where that loader is located.
> Problem: Fatal exception when NativeLoader loads same jar-packaged library twice

- configure.ac
- zproject_autotools.gsl
Solution: fix back the -Wc++compat flag that should only be in non-CXX builds
> Problem: earlier changes to warning flags in configure.ac lost logic

- zproject_cmake.gsl
This patch also:
1. Simplify Findlibzmq.cmake
2. Use both libname and linkname when they are not identical
Related issue: https://github.com/zeromq/czmq/issues/1972
> Problem: Add options to control over optional libraries

- zproject_cmake.gsl
> cmake .. -DCMAKE_TOOLCHAIN_FILE="%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake"
> ......
>-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
>
>  Target "czmq" has an INTERFACE_LINK_LIBRARIES property which differs from
its LINK_INTERFACE_LIBRARIES_DEBUG properties.
>
>  INTERFACE_LINK_LIBRARIES:
>
>    ws2_32;Rpcrt4;Iphlpapi;$<$<NOT:$<CONFIG:DEBUG>>:C:/vcpkg/installed/x86-windows/lib/libzmq-mt-4_3_2.lib>;$<$<CONFIG:DEBUG>:C:/vcpkg/installed/x86-windows/debug/lib/libzmq-mt-gd-4_3_2.lib>;E:/ProgramData/Anaconda3/Library/lib/libcurl.lib
>
>  LINK_INTERFACE_LIBRARIES_DEBUG:
> …
> Problem: CMake dev warning related to CMP0022 on Win32

- CMakeLists.txt
- zproject_travis.gsl
Most of the fixes are pre-emptive or cosmetic really, and the major one is a trivial change after hours of experiments, to remove a dash. Go figure :)
From 
````
Adding APT Sources
'sourceline' key missing:
\{"key_url"\=\>"http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_14.04/Release.key",\ "sourceline"\=\>"deb\ http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_14.04/\ ./"\}
1.59s$ sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
gpg: keyring `/tmp/tmpj85g34bj/secring.gpg' created
gpg: keyring `/tmp/tmpj85g34bj/pubring.gpg' created
gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpj85g34bj/trustdb.gpg: trustdb created
gpg: key BA9EF27F: public key "Launchpad Toolchain …
```
> Some fixes around GCC-4.9 and shadow compilation features

- zproject_class.gsl
Solution: Shuffle the test order, so private classes are tested first.
Assumption is that they are the internal implementation detail,
and if they fail their selftests in a new iteration, the public
classes would also fail for these reason (but without delivering
the real cause of failure so clearly, being higher-level consumers).
Asked-for-by: Jiri Kukacka <JiriKukacka@eaton.com>
> Problem: Private class self tests hidden by public test failures

- zproject_autotools.gsl
Solution: make the check for std::regex (assuming it means the sufficient
level of C++11 in GCC) optional with --enable-gcc-std-regex=no and by
default enabled if gcc-4.9 is requested by the project's "classfilename" tag.
A build with this option set to 'no' should compile in some of the earlier
toolchains, such as the default gcc-4.8 in "trusty" VMs on Travis, but the
result would not necessarily function (gcc-4.8 and earlier could include the
API routines for supporting the standard, but not really implement it).
Primary intended use-case:
If Travis CI tests of some projects "use" a project that by itself
requires C++11, but do not really use this aspect of it in their own
unit-tests, this is sufficient for "trusty" machines with older GCC.
In this case, the "use" tag for such project …
> Problem: test for C++11 (so g++-4.9) is unavoidable now

- zproject_java.gsl
Solution: Move the try catch block around the load library call for
android as well
> Problem: [JNI] Errors loading libs on Android are not caught

- zproject_java.gsl
Solution: Remove usage of Java 8's Stream API. Also, native-lib-loader 2.3.4 handle loading libraries for Android so there is no need for this extra check anymore.
Fix #1194
@sappo let me know if any change is necessary
> Problem: JNI bindings not compatible with Android SDK < 24

- README.md
- packaging/debian/zproject.install
- packaging/redhat/zproject.spec
- project.xml
- src/Makemodule.am
Solution: do not install `mkapi.py` and `fakecpp`. To be honest I would
personally frop them from zproject as I am not sure it even works
nowadays :)
> Problem: can't drop python from my system because of zproject

- zproject_java.gsl
Use cmake --build ., which calls the correct program according to the generator used.
Currently this doesn't work on Windows with MSVC (no make)
> Use cmake --build . instead of make

- zproject_java.gsl
- zproject_java_lib.gsl
The code generated is not correct for variadic NULL terminated methods:
https://github.com/zeromq/czmq/blob/master/bindings/jni/src/main/c/org_zeromq_czmq_Zstr.c#L71
should be
`jint sendx_ = (jint) zstr_sendx ((void *) (intptr_t) dest, string_, NULL);`
instead of
`jint sendx_ = (jint) zstr_sendx ((void *) (intptr_t) dest, string_);`
> Java: Fix variadic NULL terminated

- zproject.gsl
Solution: if a project is being just generated, and there
is already an `<include filename="license.xml">` in `project.xml`
but no `license.xml` (verbatim) file yet, create one with the content
of `<starting_year>` (set to today's year) and a `<license>` tag
with a reminder to define an actual license and regenerate.
Do not touch existing project license files though.
Example output:
````
fty-example$ cat license.xml
<starting_year>2019</starting_year>
<license>
LICENSE FOR THIS PROJECT IS NOT DEFINED!
Copyright (C) 2019- by fty-example Developers &lt;zmqbob@company.com&gt;
Please edit license.xml and populate the 'license' tag with proper
copyright and legalese contents, and regenerate the zproject.
LICENSE FOR THIS PROJECT IS NOT …
```
> Problem: default starting_year of 2015 in projects

- README.md
- project.xml
- zproject.gsl
Solution: Take legalese seriously. During regeneration, check
if the current year is mentioned (from, until, listed, whatever)
in a line with the "Copyright" word or some of the ways it can
be written in the XML `<license>` tag.
If the year is not listed in any such line (or no such lines are
there), warn the user in at least the build-logged messages, and
also pause for 5 sec so the interactive people can break, fix and
regenerate.
Loosely related to #1204 but not as invasive :)
> Problem: too easy to re-release a project with obsolete Copyrights

- zproject_cmake.gsl
re #1200
Tested on OSX Mojave (10.14.6) and XCode 11.1.
Previously a generated Xcode project would not compile because an incorrectly named .dylib file was being generated (it defaulted to "0.dylib", but our project.xml defined "0.0.1.dylib"). After some searching this might actually be a non-compliance with Apple guidelines (they want only major versions in .dylib, and minor/patch in config or something.
This edit uses sources more directly, and bypasses the whole issue.
> Fix linker issue in cmake -G Xcode projects

- zproject_java.gsl
Solution: This changes restructures the JNI bindings into three
subprojects.
* the actual binding
* a native library wrapper
* and a combiner for binding and native wrappers (currently win, osx,
linux)
In this process a lot of support has been added to allow windows
support, especially dll loading has been improved.
> Problem: JNI bindings don't generate and ship native libraries

- zproject_android.gsl
Solution: Migrate build scripts from Android NDK r11c to r20.
- Standalone toolchain
- Migration from GCC to Clang
- Migration from libgnustl to libc++
- Dropped support for API level below 16 (Android 4.1), previously it was API level 9 (Android 2.3)
- Dropped support for mips architecture
- The build script now start the build of all 4 Android architectures (arm, arm64, x86, x86_64)
> Problem: Android build script is severely outdated

- CMakeLists.txt
- builds/cmake/Modules/ClangFormat.cmake
- zproject_cmake.gsl
Solution: Use PROJECT_SOURCE_DIR and PROJECT_BINARY_DIR instead of
CMAKE_SOURCE_DIR and CMAKE_BINARY_DIR
See zeromq/czmq#2033
> Problem: czmq cannot be used as a subproject

- zproject_python_cffi.gsl
`not key in ret` checks to see if the boolean value `not key` is in `ret`. `key not in ret` checks to see if the string value `key` is not in `ret`.
> Fix 'not key in', should be 'key not in'

- zproject_travis.gsl
This PR implements the last option listed in #1217 - allowing to minimize the `project.xml` considerably, keeping just the top-level `use` tags for dependencies whose APIs are directly used by this component, e.g. https://github.com/42ity/fty-asset/pull/120/files#diff-c0a33b20a5bf94bd7bd5c012bf96f702
As detailed in #1217, this approach is not a magic silver bullet and gotta have use-cases that do not fit its idea and/or implementation.
It is recognized that this solution originated for our pain point, being "Travis Linux builds our unpackaged ecosystem from scratch with gcc/automake" (so there is no similar handling for MacOS or CMake, or non-travis builds). If the idea picks up, followers are welcome to fill the gaps.
It also introduces the notion of a new optional magical file …
> Recursive CI builds for dependencies

- zproject_cmake.gsl
Solution: only generate a private_classes entry if there are private classes.
> Problem: cmake runs private classes tests even if there are no private classes

- zproject_android.gsl
Solution: Adjust the scripts to the improved script in regard to
usability that were modified for libzmq.
These improvements include:
* Reduction of parameters that the user has to specify for each
architecture
* Initializing the build environment variable in the android_build_helper
scripts so higher level scripts can leverage them
* Renaming of TOOLCHAIN_CXXSTL to TOOLCHAIN_ABI
* Setting ANDROID_BUILD_DIR is now respected by the script and is no
longer overwritten
* New README
> Problem: Android build out of sync with upstream version from libzmq

- zproject_android.gsl
Solution: Remove copied *.la files as the contain absolute paths to their $UPSTREAM_PREFIX
> Problem: Copied la files are invalid

- zproject_git.gsl
Solution: Only use them on the root path where they are required
> Problem: Distcheck gitignore rules on all path to verbose

- zproject_java.gsl
Solution: Remove the dollar sign in front of the variable which is not
used for substitutions. Also include the projects folder in the default
value.
> Problem: JNI android build script does a bad substitution

- zproject_travis.gsl
Solution: Adjust the ci_deploy.sh and check the binding opts before
exporting the files to deploy. Also adjust the file glob where the
android jars can be found.
> Problem: Automatic JNI android release failing

- CMakeLists.txt
- builds/cmake/Modules/ClangFormat.cmake
- zproject_cmake.gsl
Solution: prevent generating custom cmake targets when they already exist.
These targets are probably not used if the project is used as a cmake subdirectory. (i.e. static linking or directly linking to the object files, used as a git submodule)
> Problem: including zproject library as cmake subdirectory fails

- zproject_class.gsl
Solution: Keep them as defined in the known projects or user defined
use's.
> Problem: Dependency headers are converted to lowercase

- CMakeLists.txt
- zproject_cmake.gsl
-O3 is not recognized by MSVC
You can use msvc with clang on windows some part of the code is not needed by it
> Windows MSVC/Clang improvements

- zproject_projects.gsl
Solution: Make the user aware of a possible miss-configuration.
Relates to #1243
> Problem: User is not warned about dropping implied uses

- packaging/obs/_service
- zproject_obs.gsl
- zproject_travis.gsl
Solution: now that tar_scm supports @PARENT_TAG@ as a revision to
automatically fetch the most recent tag on the default branch, use
it to simplify everything
https://github.com/openSUSE/obs-service-tar_scm/pull/359
> Problem: release script for OBS build fails often

- zproject_travis.gsl
Solution: clone latest tag instead
> Problem: removing latest_branch breaks ABI CI job

- zproject_class.gsl
- zproject_cmake.gsl
Solution: Use the header files as given instead.
> Problem: cmake Find files always search for header in lower case

- zproject_autotools.gsl
- zproject_class.gsl
- zproject_cmake.gsl
- zproject_projects.gsl
- zproject_travis.gsl
While resolving dependencies recursively is a nice feature there are
dependencies that are private for an dependency and the project itself
does not care for. But those private dependencies are important to know
in case we need to build them from source for a ci build.
Solution: Allow to declare dependencies as private
Implied and private dependencies are ignored as dependency but
considered for ci builds.
Includes for private dependencies are now placed in the private classes
header.
> Problem: All resolved implied dependencies are taken as project dependencies

- zproject_cmake.gsl
- zproject_travis.gsl
Solution: After we have taken every step to get an autotools script
going and weren't successful then fallback and use cmake to build the
project.
> Problem: ci scripts fail to build cmake only projects

- zproject_class.gsl
- zproject_cucumber.gsl
Solution: Enhance the selftest to support talking to multiple step def servers.
Also there was a need to split the step defs server and the step def
server runner because of how zproject manages classes and mains
> Problem: cucumber selftest doesn't support multiple step def servers

- README.md
- project.xml
- zproject_autotools.gsl
- zproject_cmake.gsl
Solution: Declare the check in the project.xml and let zproject generate
the details.
> Problem: Symbol check requires knowledge about multiple build systems

- CMakeLists.txt
- zproject_cmake.gsl
Problem: cmake find scripts generate warnings about incorrect names
Solution: use CMAKE_FIND_PACKAGE_NAME var instead of case forced var and use find_package instead of include.
LegoWelt is doing a very nice broadcast on IFM1 which gave me the support I needed to dive into this! :dancers: 
As this is hard to test and is bit of a can of worms it would be good for others to review this. I've tested this with czmq and sphactor on Linux which works.
> fix for CMake find scripts warnings

- zproject_travis.gsl
Solution: Pass BUILD_DIR as environment variable to the docker run command in the travis generator.
> Problem: Zyre travis build status is showing as failing.

- zproject.gsl
Solution: Fix invalid variable name.
As this applies in (at least) 2 places, create a function to show supported targets.
Abort after target list is given.
> Problem: Zproject crash when listing supported targets - #1284.

- zproject_autotools.gsl
In some cases they don't match, like in malamute, so the check fails
> Problem: project.prefix is used for the selftest binary, not project name

- zproject_java.gsl
Solution: Do not call zsys_handler_set() when CZMQ is not used.
Details:
Create or use a project.xml with no <use project = "czmq" />
Generate JAVA target, as usual.
Each constructor shows the following:
```
//  Disable CZMQ signal handling; allow Java to deal with it
zsys_handler_set (NULL);
```
which is buggy, since no CZMQ library will not be linked with.
> Problem: Java bindings still call zsys_handler_set (from CZMQ), when project has no CZMQ.

- zproject_class.gsl
Project constant definition:
```
<constant name = "global constant stuff" value = "123" type = "string" >
this is a
multi-line comment
for global constant
</constant>
```
Generated header file:
```
#define GLOBAL_CONSTANT_STUFF	"123" \\
this is a
multi-line comment
for global constant
```
Compilation failure:
```
make[1]: Entering directory `/home/cbox_dev/git/zproject-issues-testing'
CC       src/src_libfbp_la-foo.lo
In file included from src/../include/libfoobar.h:18:0,
from src/fbp_classes.h:35,
from src/foo.c:21:
src/../include/fbp_library.h:95:5: error: unknown type name 'this'
this is a
^
src/../include/fbp_library.h:95:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'a'
this is a
^
...
```
See #1291 for more details.
Solution: Apply a similar fix than #1283, but …
> Problem: C Compilation fails in a few cases with global constants.

- zproject_java.gsl
Example project is defined like:
```
<project
name = "Foo-Bar-Project"
script = "zproject.gsl"
url = "https://foo.bar.com//"
description = "Testing project for ZProject code generator."
prefix = "fbp"
header = "libfoobar.h">
```
Because of project prefix, build fails.
If prefix is removed from project.xml, the build goes well.
Compilation error:
```
prompt> cd bindings/jni
prompt> ./ci_build.sh
...
CMake Error at CMakeLists.txt:23 (find_package):
By not providing "Findfbp.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "fbp", but
CMake did not find one.
Could not find a package configuration file provided by "fbp" with any of
the following names:
fbpConfig.cmake
fbp-config.cmake
Add the installation prefix of "fbp" to …
```
> Problem: JAVA build fails, when project has a prefix

- zproject_delphi.gsl
Solution: Generate missing code.
Additionnally, this fixes also global/class constant names when project
name is like 'foo-bar-project' or 'Foo Bar Project'.
In both cases, we now have:
* Global constants:
```
// this is a
// multi-line comment
// for global constant
FOO_BAR_PROJECT_GLOBAL_CONSTANT_STUFF = "123";
```
* Class constants:
```
// multi-line comment
// for class constant
FOO_BAR_PROJECT_FOO_CLASS_CONSTANT_STUFF = 234;
```
Instead of invalid constant names...
Note:
There might be many more issues to solve with such project names ...
> Problem: Delphi - No code is generated for global constants.

- zproject_cmake.gsl
This prevents redundant calls to `find_package` and allows for projects including this as a subdirectory to define their own parameters for finding the dependency if CMake's `find_package` functionality is not adequate for the situation.
This applies to both required and optional packages due to CMake `find_package` not having the most graceful way of including non-system installed dependencies that are included as source in the parent project (such as a git submodule, or via `FetchContent` in CMake).
A more in-depth fix might also involve the custom `.cmake` package modules generated by `zproject` to do more checking on existing CMake package variables and not overridethem if they are already set, but that would ultimately yield the same functional result as this patch.
> Check in CMake if dependency is already found.

- zproject_java.gsl
Re-ran last zproject on CZMQ and found many differences in JAVA bindings and
git diff show the following:
```
diff --git a/bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Ztimerset.c b/bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Ztimerset.c
index 67a05848..03d77f6c 100644
--- a/bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Ztimerset.c
+++ b/bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Ztimerset.c
@@ -13,8 +13,6 @@
JNIEXPORT jlong JNICALL
Java_org_zeromq_czmq_Ztimerset__1_1new (JNIEnv *env, jclass c)
{
-    //  Disable CZMQ signal handling; allow Java to deal with it
-    zsys_handler_set (NULL);
jlong new_ = (jlong) (intptr_t) ztimerset_new ();
return new_;
}
```
Reason is PR #1292:
This PR fixes some issues on project not using CZMQ, but should
not be applied on CZMQ itself …
> Regression: CZMQ Java/Android bindings do not call zsys_set_handler() anymore.

- zproject_java.gsl
Modified zyre/bindings/jni_ci_build.sh script ends with
```
> Task :czmq-jni-native:build
Skipping task ':czmq-jni-native:build' as it has no actions.
:czmq-jni-native:build (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.0 secs.
producer locations for task group 0 (Thread[Execution worker for ':' Thread 3,5,main]) started.
producer locations for task group 0 (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.0 secs.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
BUILD …
```
> Problem: Android - Build failure on Ubuntu 22.04

- zproject_java.gsl
ZYRE compilation started for Android, with a similar script to zyre/bingings/jni/ci_build.sh.
Compilation ends with:
```
> Task :czmq-jni-native:classes UP-TO-DATE
Skipping task ':czmq-jni-native:classes' as it has no actions.
:czmq-jni-native:classes (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:czmq-jni-native:copyLibs (Thread[Execution worker for ':',5,main]) started.
> Task :czmq-jni-native:copyLibs FAILED
Caching disabled for task ':czmq-jni-native:copyLibs' because:
Build cache is disabled
Task ':czmq-jni-native:copyLibs' is not up-to-date because:
No history is available.
file or directory '/usr/java/packages/lib', not found
:czmq-jni-native:copyLibs (Thread[Execution worker for ':',5,main]) completed. Took 0.062 secs.
FAILURE: Build failed with an exception. …
```
> Problem: Compilation fails on CentOS, due to duplicate lib entry.

- zproject_delphi.gsl
This applies to method, class and constants.
When no description is given in *.api, the generated .pas files contain empty comments like:
```
//
TZsys = class
public
```
or
```
(* Zauth *)
(*  *)
```
or
```
//
CZMQ_ZFRAME_MORE = 1;
//
CZMQ_ZFRAME_REUSE = 2;
//
CZMQ_ZFRAME_DONTWAIT = 4;
```
and functions (simulated in case of CZMQ).
Solution: Avoid empty comments with a test on OBJECT.description content.
> Problem: Delphi - Empty comment generated when object has no description.

- zproject_android.gsl
function android_build_verify_so {
...
for dep_soname do
if [[ $elfoutput != *"library: [${dep_soname}]"* ]]; then
ANDROID_BUILD_FAIL+=("Library ${soname} was expected to be linked to library with soname:")
ANDROID_BUILD_FAIL+=("  ${dep_soname}")
fi
done
The for xxx syntax is wrong, most probably a typo somewhere.
Solution: Fix & complete the for xxx loop. 
Tested with & without LIBSODIUM (only available dependent library for LIBZMQ).
Fixed in LIBZMQ (https://github.com/zeromq/libzmq/pull/4431), reported to ZPROJECT.
> Problem: Android helpers no not validate dependent libraries.

- zproject_android.gsl
A call to `<CZMQ>/builds/android/ci_build.sh` shows the following:
```
fatal: unable to update url base from redirection:
asked for: https://gnunet.org/git/libmicrohttpd.git/info/refs?service=git-upload-pack
redirect: https://git.gnunet.org/
```
The generated code in `<CZMQ>/builds/android/ci_build.sh` is:
```
export LIBMICROHTTPD_ROOT="/tmp/tmp-deps/libmicrohttpd"
git clone --quiet --depth 1 https://gnunet.org/git/libmicrohttpd.git $LIBMICROHTTPD_ROOT
```
The same kind of download in `<CZMQ>/bindings/jni/ci_build.sh` looks like:
```
export LIBMICROHTTPD_ROOT="/tmp/tmp-deps/libmicrohttpd"
wget http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.44.tar.gz
tar -xzf $(basename "http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.44.tar.gz")
mv $(basename …
```
> Problem: builds/android/ci_build.sh must download tarball, when required.

- zproject_skeletons.gsl
Scenario:
```
cd zyre
rm -f include/zyre.h
(export PATH=$PWD/../zproject:$PATH; ./generate.sh)
```
Result:
```
...
gsl/4 M: W: in zyre event: 'zmsg' does not resolve to a class
gsl/4 M: W: in zyre event: 'zmsg' does not resolve to a class
gsl/4 M: NOT regenerating an existing include/zyre.h skeleton file; but you probably should not care
gsl/4 M: Generating skeleton for include/zyre.h
(zproject_skeletons.gsl 358) Undefined expression: project.headerext
```
Reason:
Typo introduced in zproject_skeletons.gsl:
https://github.com/zeromq/zproject/blame/master/zproject_skeletons.gsl#L358
Instead of:
```
#include "$(class.name)_library.$(project.headerext)"
```
it should be (like in other places):
```
#include "$(class.name)_library.$(project.header_ext)"
```
Solution: Fix typo.
> Problem: ZProject fails to regenerate ZYRE/include/zyre.h

- zproject_android.gsl
- zproject_java.gsl
Goal is to make possible to have a modification in ZProject and check its impact on CZMQ/ZYRE before an official PR to any of them, like below:
```
export MY_DEPENDENCY_ROOT=${HOME}/my_dependency
cd $MY_DEPENDENCY_ROOT
gsl project.xml
cd <project>/bindings/jni
./ci_build.sh
```
Solution: Clone (or download) only if ${XXX_ROOT} is set and folder does not exist.
Supported environment variables XXX_ROOT are placed at the begining of the file, with their current (and unchanged) default value:
```
export XXX_ROOT=${XXX_ROOT:-<default_value>}
```
> Problem: CI build scripts should allow existing dependency folders.

- zproject_android.gsl
Proposal is to dump ./configure options to have an output like below:
```
LIBZMQ (x86_64) - ./configure options to build 'LIBZMQ':
> --quiet
> TOOLCHAIN=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
> CC=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang
> CXX=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++
> LD=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/ld
> AS=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as
> AR=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
> RANLIB=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
> STRIP=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
> …
```
> Problem: Android build system needs some debug (./configure options)

- zproject_android.gsl
- zproject_java.gsl
Same cause than explained in
https://github.com/zeromq/libzmq/pull/4437
Solution: Fix invalid LDFLAGS.
Notes:
- Still fails on physical devices.
> Problem: Android APP fails to load ZMQ since NDK r25.x

- zproject_android.gsl
A few enhancements/code review/shellcheck fixes have been applied recently to Android helpers in LIBZMQ. New helper functions, variables, checks,... were added. All can be of interest for CZMQ, ZYRE but also for any other zproject-generated ilbrary.
Solution: Report Android helper modifications in one shot from LIBZMQ to ZPROJECT.
This concerns only the helpers. CI build scripts are not impacted for now, as they may require more specific tests, but they will follow the same soon.
Method:
- Manual report of LIBZMQ helper modifications to CZMQ & ZYRE.
- Check all still compile fine. --> This gives CZMQ & ZYRE "expected source tree".
- Report the modifications to ZPROJECT.
- Call GSL to generate CZMQ & ZYRE bindings.
- Diff between generated code and their "expected source tree".
- Check all …
> Problem: Android build helpers not in sync with LIBZMQ.

- zproject_java.gsl
Since last Saturday, Android build fails with:
FAILURE: Build failed with an exception.
* Where:
Build file '/builds/CrisalidBox/zproject-android-testing/zyre/bindings/jni/zyre-jni/build.gradle' line: 25
* What went wrong:
A problem occurred evaluating project ':zyre-jni'.
> Could not resolve all files for configuration ':zyre-jni:runtimeClasspath'.
> Could not resolve org.zeromq.czmq:czmq-jni:latest.integration.
Required by:
project :zyre-jni
> Failed to list versions for org.zeromq.czmq:czmq-jni.
> Unable to load Maven meta-data from https://jcenter.bintray.com/org/zeromq/czmq/czmq-jni/maven-metadata.xml.
> Could not GET 'https://jcenter.bintray.com/org/zeromq/czmq/czmq-jni/maven-metadata.xml'.
> Read timed out
https://jcenter.bintray.com/ does not respond at all any more:
prompt> wget …
> Summary: Problem: Android build fails due to use of JCenter

- zproject_java.gsl
2 reasons to revert:
- Former PR is incomplete and breaks "release" Android builds ("snapshot" are not impacted).
A complete solution would involve another artifact repository.
- Jcenter/Bintray are back in service, after outage.
> Revert "Summary: Problem: Android build fails due to use of JCenter"

- zproject_java.gsl
Reasons:
- ZYRE tests fail if the host firewall blocks ZRE or any other required port.
- ZYRE tests may fail if 2 or more tests are launched in parallel (SHOUT messages are received by the wrong test client).
Solution: Provide a variable to pass specific options to GRADLEW.
How to use:
export ZYRE_GRADLEW_OPTS="-x test"
cd zyre/bindings/jni
./ci_build.sh
ZYRE CI build scripts also builds CZMQ, with a different call to GRADLEW. To pass options to CZMQ GRADLEW, use the following:
export CZMQ_GRADLEW_OPTS="xxx"
cd zyre/bindings/jni
./ci_build.sh
If one wants to disable ZYRE & CZMQ gradlew automatic tests, use the following:
export CZMQ_GRADLEW_OPTS="-x test"
export ZYRE_GRADLEW_OPTS="-x test"
cd zyre/bindings/jni
./ci_build.sh
Note: This adds another possibility to build ZYRE JNI releases. …
> Problem: Android CI build need a way to disable GRADLE automatic tests.

- zproject_android.gsl
- zproject_java.gsl
Solution: Apply similar modifications than in LIBZMQ.
Modificationts & enhancements apply in:
* builds/android/*
* bindings/jni/ci_build.sh
* bindings/jni/README.md
* bindings/jni/xxx-jni/android/build.sh
Android helpers do not use /tmp anymore to clone & build dependencies. This was causing conflicts, when there were 2 parallel compilations:
* builds/android/.deps: used to specify a path, where to download dependencies (instead of /tmp/tmp-deps).
* builds/android/.build: used to "install" the dependency binaries (instead of /tmp/android_build).
* /tmp/cache: no more used
Android helpers are enriched with new functions to download & build dependencies.
* The new build function is able to (and used to) perform native and cross-compilation of dependencies.
* Added ANDROID_DEPENDENCIES_DIR …
> Problem: ZProject ANDROID build scripts and documentations are not up-to-date, compared to LIBZMQ.

- README.md
- zproject_known_projects.xml
Solution: Fix repository and add tarball info
Got tarball info from CZMQ project.xml.
> Problem: ZProject model has invalid info for libmicrohttpd.

- README.md
- README.txt
- project.xml
- zproject_android.gsl
- zproject_java.gsl
For an Android library, NDK and SDK can be considered as project-wide values. As such, they can be part of the project.xml, via 2 target options.
Solution: Create android target options "ndk_version" and "min_sdk_version".
Example in project.xml:
<target name = "android" >
<option name = "android_ndk_version" value = "android-dnk-r23"/>
<option name = "min_sdk_version" value = "21"/>
</ target>
If these options are not specified (like CZMQ & ZYRE), the ZProject hard coded values apply.
If specified, they can be overriden with the `export` mechanism already in place and explained in generated `builds/android/README.md` and `bindings/jni/README.md`.
ZProject documentation is updated with the same.
> Problem: Android target needs options to specify project NDK & min SDK default values.

- zproject_android.gsl
- zproject_java.gsl
Some generated scripts are built with `$(USE.PROJECT)_ROOT` and some others are built with `$(USE.LIBNAME)_ROOT`
This inconsistency is not seen with CZMQ.
With ZYRE, this gives (for instance):
* bindings/jni/ci_build.sh set LIBCZMQ_ROOT:
android_init_dependency_root "libczmq"   # Check or initialize LIBCZMQ_ROOT
* builds/android/build.sh expects CZMQ_ROOT:
if [ ! -d "${CZMQ_ROOT}" ] ; then
Solution: Replace `$(USE.LIBNAME)_ROOT` by `$(USE.PROJECT)_ROOT` and similar.
**Important:**
This will affect ZYRE, when using recent commits, and especially like below:
export LIBCZMQ_ROOT=xxx
cd bindings/jni/zyre-jni/android/build.sh:
./build.sh [arm|arm64|x86|x86_64]
The same call becomes:
export CZMQ_ROOT=xxx
cd bindings/jni/zyre-jni/android/build.sh:
./build.sh [arm|arm64|x86|x86_64]
or similar …
> Problem: Android generated code has inconsistent dependency ROOT variable names.

- zproject_android.gsl
- zproject_java.gsl
Issue seen with a specific scenario, with ZYRE.
CZMQ is not pre-downloaded and get confused with a pre-set value for LIBZMQ_ROOT.
Solution: Init XXX_ROOT and fetch dependencies right after.
> Problem: Android build fail with recent PR and sub-dependencies (LIBZMQ) 

- zproject_android.gsl
Due to a kind of "padding" generated by GSL.
Solution: use escape '\' to avoid this padding.
> Problem: Android helper has unexpected diff with LIBZMQ's one.

- zproject_java.gsl
Problem detected with the following project.xml:
<project
name     = "MyAwesomeProject"
prefix   = "map"
libname  = "libawesome"
linkname = "awesome"
...
</project>
results in:
...
Make Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
See also "/home/stephan/git/zproject-android-testing/MyTortureTest/bindings/jni/map-jni/build/CMakeFiles/CMakeOutput.log".
Could NOT find map (missing: map_LIBRARIES)
Call Stack (most recent call first):
/usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:621 (_FPHSA_FAILURE_MESSAGE)
Findmap.cmake:35 (find_package_handle_standard_args)
CMakeLists.txt:23 (find_package)
Reason is found in the generated bindings/jni/map-jni/Findmap.cmake:
find_library (
${CMAKE_FIND_PACKAGE_NAME}_LIBRARIES
NAMES map
HINTS …
> Problem: Android build fails if linkname is different than prefix

- CMakeLists.txt
The Findgsl.cmake defined "GSL_FOUND", this fix uses the same case as seen in the .cmake file.
> Fix typo with GSL_FOUND

- zproject_ruby.gsl
Solution: create FFI::MemoryPointer in advance
> Problem: Ruby binding: object allocation during GC

- packaging/redhat/zproject.spec
- zproject_redhat.gsl
Solution: generate the same dummy entry as the Debian changelog
> Problem: SUSE builds fail due to empty changelog in spec file

- configure.ac
See also https://github.com/zeromq/libzmq/commit/3b264019a24b08246e8a75f5014f893d7b6ffef9.
configure scripts need to be runnable with a POSIX-compliant /bin/sh.
On many (but not all!) systems, /bin/sh is provided by Bash, so errors like this aren't spotted. Notably Debian defaults to /bin/sh provided by dash which doesn't tolerate such bashisms as '=='.
This retains compatibility with bash.
> configure: fix bashisms

- zproject_autotools.gsl
A basic project.xml fails with ENABLE_MYPROJECT_SELFTEST does not appear in AM_CONDITIONAL.
This project.xml:
```xml
<project script = "zproject.gsl">
<main name = "hello" private = "1" />
</project>
```
results in the following error when `./autogen.sh` is executed:
```
configure.ac:55: installing 'config/compile'
configure.ac:58: installing 'config/config.guess'
configure.ac:58: installing 'config/config.sub'
configure.ac:21: installing 'config/install-sh'
configure.ac:21: installing 'config/missing'
src/Makemodule.am:20: error: ENABLE_MYPROJECT_SELFTEST does not appear in AM_CONDITIONAL
Makefile.am:44:   'src/Makemodule.am' included from here
src/Makemodule.am:319: error: ENABLE_MYPROJECT_SELFTEST does not appear in AM_CONDITIONAL
Makefile.am:44:   'src/Makemodule.am' included from …
```
> Problem:  autogen fails from SELFTEST missing in configure.am

- zproject_ruby.gsl
Solution: Also look for my_lib.so.X where X is the major version
* on Debian/Ubuntu, my_lib.so is only available with mylib-dev installed (e.g. libczmq-dev)
* it used to look just for my_lib.so in the search paths
* add LD_LIBRARY_PATH and /usr/lib to search paths
> Problem: Ruby binding can't find lib without devel package installed

- zproject_cmake.gsl
This will fix:
- https://github.com/zeromq/zproject/issues/1347
- https://github.com/zeromq/czmq/issues/2313
- CZMQ CI actions
Note: ZYRE must be regenerated with the whole stuff around CMake 4 support.
> Problem: CMakeLists.txt generation broken since CMake 4 support.
